/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.BreedingRecord;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Breeding extends TableImpl<BreedingRecord> {

    private static final long serialVersionUID = 1913806833;

    /**
     * The reference instance of <code>handycapper.breeding</code>
     */
    public static final Breeding BREEDING = new Breeding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BreedingRecord> getRecordType() {
        return BreedingRecord.class;
    }

    /**
     * The column <code>handycapper.breeding.id</code>.
     */
    public final TableField<BreedingRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('breeding_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.breeding.starter_id</code>.
     */
    public final TableField<BreedingRecord, Integer> STARTER_ID = createField("starter_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.breeding.horse</code>.
     */
    public final TableField<BreedingRecord, String> HORSE = createField("horse", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>handycapper.breeding.color</code>.
     */
    public final TableField<BreedingRecord, String> COLOR = createField("color", org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>handycapper.breeding.sex</code>.
     */
    public final TableField<BreedingRecord, String> SEX = createField("sex", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.breeding.sire</code>.
     */
    public final TableField<BreedingRecord, String> SIRE = createField("sire", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.breeding.dam</code>.
     */
    public final TableField<BreedingRecord, String> DAM = createField("dam", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.breeding.dam_sire</code>.
     */
    public final TableField<BreedingRecord, String> DAM_SIRE = createField("dam_sire", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.breeding.foaling_date</code>.
     */
    public final TableField<BreedingRecord, Date> FOALING_DATE = createField("foaling_date", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>handycapper.breeding.foaling_location</code>.
     */
    public final TableField<BreedingRecord, String> FOALING_LOCATION = createField("foaling_location", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.breeding.breeder</code>.
     */
    public final TableField<BreedingRecord, String> BREEDER = createField("breeder", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>handycapper.breeding</code> table reference
     */
    public Breeding() {
        this(DSL.name("breeding"), null);
    }

    /**
     * Create an aliased <code>handycapper.breeding</code> table reference
     */
    public Breeding(String alias) {
        this(DSL.name(alias), BREEDING);
    }

    /**
     * Create an aliased <code>handycapper.breeding</code> table reference
     */
    public Breeding(Name alias) {
        this(alias, BREEDING);
    }

    private Breeding(Name alias, Table<BreedingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Breeding(Name alias, Table<BreedingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BreedingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BREEDING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Breeding as(String alias) {
        return new Breeding(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Breeding as(Name alias) {
        return new Breeding(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Breeding rename(String name) {
        return new Breeding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Breeding rename(Name name) {
        return new Breeding(name, null);
    }
}
