/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.CancelledRecord;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cancelled extends TableImpl<CancelledRecord> {

    private static final long serialVersionUID = 582270807;

    /**
     * The reference instance of <code>handycapper.cancelled</code>
     */
    public static final Cancelled CANCELLED = new Cancelled();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CancelledRecord> getRecordType() {
        return CancelledRecord.class;
    }

    /**
     * The column <code>handycapper.cancelled.id</code>.
     */
    public final TableField<CancelledRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('cancelled_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.cancelled.reason</code>.
     */
    public final TableField<CancelledRecord, String> REASON = createField("reason", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.cancelled.date</code>.
     */
    public final TableField<CancelledRecord, Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>handycapper.cancelled.track</code>.
     */
    public final TableField<CancelledRecord, String> TRACK = createField("track", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>handycapper.cancelled.track_canonical</code>.
     */
    public final TableField<CancelledRecord, String> TRACK_CANONICAL = createField("track_canonical", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>handycapper.cancelled.track_state</code>.
     */
    public final TableField<CancelledRecord, String> TRACK_STATE = createField("track_state", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>handycapper.cancelled.track_country</code>.
     */
    public final TableField<CancelledRecord, String> TRACK_COUNTRY = createField("track_country", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>handycapper.cancelled.track_name</code>.
     */
    public final TableField<CancelledRecord, String> TRACK_NAME = createField("track_name", org.jooq.impl.SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>handycapper.cancelled.number</code>.
     */
    public final TableField<CancelledRecord, Integer> NUMBER = createField("number", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>handycapper.cancelled</code> table reference
     */
    public Cancelled() {
        this(DSL.name("cancelled"), null);
    }

    /**
     * Create an aliased <code>handycapper.cancelled</code> table reference
     */
    public Cancelled(String alias) {
        this(DSL.name(alias), CANCELLED);
    }

    /**
     * Create an aliased <code>handycapper.cancelled</code> table reference
     */
    public Cancelled(Name alias) {
        this(alias, CANCELLED);
    }

    private Cancelled(Name alias, Table<CancelledRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cancelled(Name alias, Table<CancelledRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CancelledRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CANCELLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cancelled as(String alias) {
        return new Cancelled(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cancelled as(Name alias) {
        return new Cancelled(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cancelled rename(String name) {
        return new Cancelled(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cancelled rename(Name name) {
        return new Cancelled(name, null);
    }
}
