/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.EquipRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Equip extends TableImpl<EquipRecord> {

    private static final long serialVersionUID = 572087666;

    /**
     * The reference instance of <code>handycapper.equip</code>
     */
    public static final Equip EQUIP = new Equip();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EquipRecord> getRecordType() {
        return EquipRecord.class;
    }

    /**
     * The column <code>handycapper.equip.id</code>.
     */
    public final TableField<EquipRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('equip_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.equip.starter_id</code>.
     */
    public final TableField<EquipRecord, Integer> STARTER_ID = createField("starter_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.equip.code</code>.
     */
    public final TableField<EquipRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>handycapper.equip.text</code>.
     */
    public final TableField<EquipRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * Create a <code>handycapper.equip</code> table reference
     */
    public Equip() {
        this(DSL.name("equip"), null);
    }

    /**
     * Create an aliased <code>handycapper.equip</code> table reference
     */
    public Equip(String alias) {
        this(DSL.name(alias), EQUIP);
    }

    /**
     * Create an aliased <code>handycapper.equip</code> table reference
     */
    public Equip(Name alias) {
        this(alias, EQUIP);
    }

    private Equip(Name alias, Table<EquipRecord> aliased) {
        this(alias, aliased, null);
    }

    private Equip(Name alias, Table<EquipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EquipRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EQUIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Equip as(String alias) {
        return new Equip(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Equip as(Name alias) {
        return new Equip(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Equip rename(String name) {
        return new Equip(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Equip rename(Name name) {
        return new Equip(name, null);
    }
}
