/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.ExoticsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exotics extends TableImpl<ExoticsRecord> {

    private static final long serialVersionUID = -584263490;

    /**
     * The reference instance of <code>handycapper.exotics</code>
     */
    public static final Exotics EXOTICS = new Exotics();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExoticsRecord> getRecordType() {
        return ExoticsRecord.class;
    }

    /**
     * The column <code>handycapper.exotics.id</code>.
     */
    public final TableField<ExoticsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('exotics_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.exotics.race_id</code>.
     */
    public final TableField<ExoticsRecord, Integer> RACE_ID = createField("race_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.exotics.unit</code>.
     */
    public final TableField<ExoticsRecord, Double> UNIT = createField("unit", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.exotics.name</code>.
     */
    public final TableField<ExoticsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.exotics.winning_numbers</code>.
     */
    public final TableField<ExoticsRecord, String> WINNING_NUMBERS = createField("winning_numbers", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.exotics.payoff</code>.
     */
    public final TableField<ExoticsRecord, Double> PAYOFF = createField("payoff", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.exotics.odds</code>.
     */
    public final TableField<ExoticsRecord, Double> ODDS = createField("odds", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.exotics.number_correct</code>.
     */
    public final TableField<ExoticsRecord, Integer> NUMBER_CORRECT = createField("number_correct", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.exotics.pool</code>.
     */
    public final TableField<ExoticsRecord, Double> POOL = createField("pool", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.exotics.carryover</code>.
     */
    public final TableField<ExoticsRecord, Double> CARRYOVER = createField("carryover", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>handycapper.exotics</code> table reference
     */
    public Exotics() {
        this(DSL.name("exotics"), null);
    }

    /**
     * Create an aliased <code>handycapper.exotics</code> table reference
     */
    public Exotics(String alias) {
        this(DSL.name(alias), EXOTICS);
    }

    /**
     * Create an aliased <code>handycapper.exotics</code> table reference
     */
    public Exotics(Name alias) {
        this(alias, EXOTICS);
    }

    private Exotics(Name alias, Table<ExoticsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Exotics(Name alias, Table<ExoticsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExoticsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EXOTICS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Exotics as(String alias) {
        return new Exotics(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Exotics as(Name alias) {
        return new Exotics(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Exotics rename(String name) {
        return new Exotics(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Exotics rename(Name name) {
        return new Exotics(name, null);
    }
}
