/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.FractionalsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Fractionals extends TableImpl<FractionalsRecord> {

    private static final long serialVersionUID = 38419142;

    /**
     * The reference instance of <code>handycapper.fractionals</code>
     */
    public static final Fractionals FRACTIONALS = new Fractionals();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FractionalsRecord> getRecordType() {
        return FractionalsRecord.class;
    }

    /**
     * The column <code>handycapper.fractionals.id</code>.
     */
    public final TableField<FractionalsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('fractionals_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.fractionals.race_id</code>.
     */
    public final TableField<FractionalsRecord, Integer> RACE_ID = createField("race_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.fractionals.point</code>.
     */
    public final TableField<FractionalsRecord, Integer> POINT = createField("point", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.fractionals.text</code>.
     */
    public final TableField<FractionalsRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>handycapper.fractionals.compact</code>.
     */
    public final TableField<FractionalsRecord, String> COMPACT = createField("compact", org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>handycapper.fractionals.feet</code>.
     */
    public final TableField<FractionalsRecord, Integer> FEET = createField("feet", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.fractionals.furlongs</code>.
     */
    public final TableField<FractionalsRecord, Double> FURLONGS = createField("furlongs", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>handycapper.fractionals.time</code>.
     */
    public final TableField<FractionalsRecord, String> TIME = createField("time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.fractionals.millis</code>.
     */
    public final TableField<FractionalsRecord, Long> MILLIS = createField("millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>handycapper.fractionals</code> table reference
     */
    public Fractionals() {
        this(DSL.name("fractionals"), null);
    }

    /**
     * Create an aliased <code>handycapper.fractionals</code> table reference
     */
    public Fractionals(String alias) {
        this(DSL.name(alias), FRACTIONALS);
    }

    /**
     * Create an aliased <code>handycapper.fractionals</code> table reference
     */
    public Fractionals(Name alias) {
        this(alias, FRACTIONALS);
    }

    private Fractionals(Name alias, Table<FractionalsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Fractionals(Name alias, Table<FractionalsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<FractionalsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FRACTIONALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Fractionals as(String alias) {
        return new Fractionals(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Fractionals as(Name alias) {
        return new Fractionals(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Fractionals rename(String name) {
        return new Fractionals(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Fractionals rename(Name name) {
        return new Fractionals(name, null);
    }
}
