/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.IndivSplitsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndivSplits extends TableImpl<IndivSplitsRecord> {

    private static final long serialVersionUID = -2077994402;

    /**
     * The reference instance of <code>handycapper.indiv_splits</code>
     */
    public static final IndivSplits INDIV_SPLITS = new IndivSplits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndivSplitsRecord> getRecordType() {
        return IndivSplitsRecord.class;
    }

    /**
     * The column <code>handycapper.indiv_splits.id</code>.
     */
    public final TableField<IndivSplitsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('indiv_splits_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.indiv_splits.starter_id</code>.
     */
    public final TableField<IndivSplitsRecord, Integer> STARTER_ID = createField("starter_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_splits.point</code>.
     */
    public final TableField<IndivSplitsRecord, Integer> POINT = createField("point", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_splits.text</code>.
     */
    public final TableField<IndivSplitsRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR(25).nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_splits.compact</code>.
     */
    public final TableField<IndivSplitsRecord, String> COMPACT = createField("compact", org.jooq.impl.SQLDataType.VARCHAR(35).nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_splits.feet</code>.
     */
    public final TableField<IndivSplitsRecord, Integer> FEET = createField("feet", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_splits.furlongs</code>.
     */
    public final TableField<IndivSplitsRecord, Double> FURLONGS = createField("furlongs", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_splits.time</code>.
     */
    public final TableField<IndivSplitsRecord, String> TIME = createField("time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.indiv_splits.millis</code>.
     */
    public final TableField<IndivSplitsRecord, Long> MILLIS = createField("millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>handycapper.indiv_splits.from_point</code>.
     */
    public final TableField<IndivSplitsRecord, Integer> FROM_POINT = createField("from_point", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.indiv_splits.from_text</code>.
     */
    public final TableField<IndivSplitsRecord, String> FROM_TEXT = createField("from_text", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.indiv_splits.from_compact</code>.
     */
    public final TableField<IndivSplitsRecord, String> FROM_COMPACT = createField("from_compact", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.indiv_splits.from_feet</code>.
     */
    public final TableField<IndivSplitsRecord, Integer> FROM_FEET = createField("from_feet", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.indiv_splits.from_furlongs</code>.
     */
    public final TableField<IndivSplitsRecord, Double> FROM_FURLONGS = createField("from_furlongs", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.indiv_splits.from_time</code>.
     */
    public final TableField<IndivSplitsRecord, String> FROM_TIME = createField("from_time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.indiv_splits.from_millis</code>.
     */
    public final TableField<IndivSplitsRecord, Long> FROM_MILLIS = createField("from_millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>handycapper.indiv_splits.to_point</code>.
     */
    public final TableField<IndivSplitsRecord, Integer> TO_POINT = createField("to_point", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.indiv_splits.to_text</code>.
     */
    public final TableField<IndivSplitsRecord, String> TO_TEXT = createField("to_text", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.indiv_splits.to_compact</code>.
     */
    public final TableField<IndivSplitsRecord, String> TO_COMPACT = createField("to_compact", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.indiv_splits.to_feet</code>.
     */
    public final TableField<IndivSplitsRecord, Integer> TO_FEET = createField("to_feet", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.indiv_splits.to_furlongs</code>.
     */
    public final TableField<IndivSplitsRecord, Double> TO_FURLONGS = createField("to_furlongs", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.indiv_splits.to_time</code>.
     */
    public final TableField<IndivSplitsRecord, String> TO_TIME = createField("to_time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.indiv_splits.to_millis</code>.
     */
    public final TableField<IndivSplitsRecord, Long> TO_MILLIS = createField("to_millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>handycapper.indiv_splits</code> table reference
     */
    public IndivSplits() {
        this(DSL.name("indiv_splits"), null);
    }

    /**
     * Create an aliased <code>handycapper.indiv_splits</code> table reference
     */
    public IndivSplits(String alias) {
        this(DSL.name(alias), INDIV_SPLITS);
    }

    /**
     * Create an aliased <code>handycapper.indiv_splits</code> table reference
     */
    public IndivSplits(Name alias) {
        this(alias, INDIV_SPLITS);
    }

    private IndivSplits(Name alias, Table<IndivSplitsRecord> aliased) {
        this(alias, aliased, null);
    }

    private IndivSplits(Name alias, Table<IndivSplitsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IndivSplitsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_INDIV_SPLITS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivSplits as(String alias) {
        return new IndivSplits(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivSplits as(Name alias) {
        return new IndivSplits(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndivSplits rename(String name) {
        return new IndivSplits(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndivSplits rename(Name name) {
        return new IndivSplits(name, null);
    }
}
