/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.IndivRatingsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndivRatings extends TableImpl<IndivRatingsRecord> {

    private static final long serialVersionUID = -1747027833;

    /**
     * The reference instance of <code>handycapper.indiv_ratings</code>
     */
    public static final IndivRatings INDIV_RATINGS = new IndivRatings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndivRatingsRecord> getRecordType() {
        return IndivRatingsRecord.class;
    }

    /**
     * The column <code>handycapper.indiv_ratings.id</code>.
     */
    public final TableField<IndivRatingsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('indiv_ratings_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.indiv_ratings.starter_id</code>.
     */
    public final TableField<IndivRatingsRecord, Integer> STARTER_ID = createField("starter_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_ratings.name</code>.
     */
    public final TableField<IndivRatingsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.indiv_ratings.text</code>.
     */
    public final TableField<IndivRatingsRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.indiv_ratings.value</code>.
     */
    public final TableField<IndivRatingsRecord, Double> VALUE = createField("value", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.indiv_ratings.extra</code>.
     */
    public final TableField<IndivRatingsRecord, String> EXTRA = createField("extra", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * Create a <code>handycapper.indiv_ratings</code> table reference
     */
    public IndivRatings() {
        this(DSL.name("indiv_ratings"), null);
    }

    /**
     * Create an aliased <code>handycapper.indiv_ratings</code> table reference
     */
    public IndivRatings(String alias) {
        this(DSL.name(alias), INDIV_RATINGS);
    }

    /**
     * Create an aliased <code>handycapper.indiv_ratings</code> table reference
     */
    public IndivRatings(Name alias) {
        this(alias, INDIV_RATINGS);
    }

    private IndivRatings(Name alias, Table<IndivRatingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private IndivRatings(Name alias, Table<IndivRatingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IndivRatingsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_INDIV_RATINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivRatings as(String alias) {
        return new IndivRatings(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivRatings as(Name alias) {
        return new IndivRatings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndivRatings rename(String name) {
        return new IndivRatings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndivRatings rename(Name name) {
        return new IndivRatings(name, null);
    }
}
