/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.IndivFractionalsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndivFractionals extends TableImpl<IndivFractionalsRecord> {

    private static final long serialVersionUID = 1486781549;

    /**
     * The reference instance of <code>handycapper.indiv_fractionals</code>
     */
    public static final IndivFractionals INDIV_FRACTIONALS = new IndivFractionals();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IndivFractionalsRecord> getRecordType() {
        return IndivFractionalsRecord.class;
    }

    /**
     * The column <code>handycapper.indiv_fractionals.id</code>.
     */
    public final TableField<IndivFractionalsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('indiv_fractionals_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.indiv_fractionals.starter_id</code>.
     */
    public final TableField<IndivFractionalsRecord, Integer> STARTER_ID = createField("starter_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_fractionals.point</code>.
     */
    public final TableField<IndivFractionalsRecord, Integer> POINT = createField("point", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_fractionals.text</code>.
     */
    public final TableField<IndivFractionalsRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_fractionals.compact</code>.
     */
    public final TableField<IndivFractionalsRecord, String> COMPACT = createField("compact", org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_fractionals.feet</code>.
     */
    public final TableField<IndivFractionalsRecord, Integer> FEET = createField("feet", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_fractionals.furlongs</code>.
     */
    public final TableField<IndivFractionalsRecord, Double> FURLONGS = createField("furlongs", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>handycapper.indiv_fractionals.time</code>.
     */
    public final TableField<IndivFractionalsRecord, String> TIME = createField("time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.indiv_fractionals.millis</code>.
     */
    public final TableField<IndivFractionalsRecord, Long> MILLIS = createField("millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>handycapper.indiv_fractionals</code> table reference
     */
    public IndivFractionals() {
        this(DSL.name("indiv_fractionals"), null);
    }

    /**
     * Create an aliased <code>handycapper.indiv_fractionals</code> table reference
     */
    public IndivFractionals(String alias) {
        this(DSL.name(alias), INDIV_FRACTIONALS);
    }

    /**
     * Create an aliased <code>handycapper.indiv_fractionals</code> table reference
     */
    public IndivFractionals(Name alias) {
        this(alias, INDIV_FRACTIONALS);
    }

    private IndivFractionals(Name alias, Table<IndivFractionalsRecord> aliased) {
        this(alias, aliased, null);
    }

    private IndivFractionals(Name alias, Table<IndivFractionalsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<IndivFractionalsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_INDIV_FRACTIONALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivFractionals as(String alias) {
        return new IndivFractionals(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivFractionals as(Name alias) {
        return new IndivFractionals(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IndivFractionals rename(String name) {
        return new IndivFractionals(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IndivFractionals rename(Name name) {
        return new IndivFractionals(name, null);
    }
}
