/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.MedsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Meds extends TableImpl<MedsRecord> {

    private static final long serialVersionUID = -1322281853;

    /**
     * The reference instance of <code>handycapper.meds</code>
     */
    public static final Meds MEDS = new Meds();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MedsRecord> getRecordType() {
        return MedsRecord.class;
    }

    /**
     * The column <code>handycapper.meds.id</code>.
     */
    public final TableField<MedsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('meds_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.meds.starter_id</code>.
     */
    public final TableField<MedsRecord, Integer> STARTER_ID = createField("starter_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.meds.code</code>.
     */
    public final TableField<MedsRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.CHAR(1), this, "");

    /**
     * The column <code>handycapper.meds.text</code>.
     */
    public final TableField<MedsRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * Create a <code>handycapper.meds</code> table reference
     */
    public Meds() {
        this(DSL.name("meds"), null);
    }

    /**
     * Create an aliased <code>handycapper.meds</code> table reference
     */
    public Meds(String alias) {
        this(DSL.name(alias), MEDS);
    }

    /**
     * Create an aliased <code>handycapper.meds</code> table reference
     */
    public Meds(Name alias) {
        this(alias, MEDS);
    }

    private Meds(Name alias, Table<MedsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Meds(Name alias, Table<MedsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MedsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MEDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Meds as(String alias) {
        return new Meds(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Meds as(Name alias) {
        return new Meds(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Meds rename(String name) {
        return new Meds(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Meds rename(Name name) {
        return new Meds(name, null);
    }
}
