/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.PointsOfCallRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PointsOfCall extends TableImpl<PointsOfCallRecord> {

    private static final long serialVersionUID = -848749221;

    /**
     * The reference instance of <code>handycapper.points_of_call</code>
     */
    public static final PointsOfCall POINTS_OF_CALL = new PointsOfCall();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PointsOfCallRecord> getRecordType() {
        return PointsOfCallRecord.class;
    }

    /**
     * The column <code>handycapper.points_of_call.id</code>.
     */
    public final TableField<PointsOfCallRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('points_of_call_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.points_of_call.starter_id</code>.
     */
    public final TableField<PointsOfCallRecord, Integer> STARTER_ID = createField("starter_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.points_of_call.point</code>.
     */
    public final TableField<PointsOfCallRecord, Integer> POINT = createField("point", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.points_of_call.text</code>.
     */
    public final TableField<PointsOfCallRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>handycapper.points_of_call.compact</code>.
     */
    public final TableField<PointsOfCallRecord, String> COMPACT = createField("compact", org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>handycapper.points_of_call.feet</code>.
     */
    public final TableField<PointsOfCallRecord, Integer> FEET = createField("feet", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.points_of_call.furlongs</code>.
     */
    public final TableField<PointsOfCallRecord, Double> FURLONGS = createField("furlongs", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.points_of_call.position</code>.
     */
    public final TableField<PointsOfCallRecord, Integer> POSITION = createField("position", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.points_of_call.len_ahead_text</code>.
     */
    public final TableField<PointsOfCallRecord, String> LEN_AHEAD_TEXT = createField("len_ahead_text", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.points_of_call.len_ahead</code>.
     */
    public final TableField<PointsOfCallRecord, Double> LEN_AHEAD = createField("len_ahead", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.points_of_call.tot_len_bhd_text</code>.
     */
    public final TableField<PointsOfCallRecord, String> TOT_LEN_BHD_TEXT = createField("tot_len_bhd_text", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.points_of_call.tot_len_bhd</code>.
     */
    public final TableField<PointsOfCallRecord, Double> TOT_LEN_BHD = createField("tot_len_bhd", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.points_of_call.wide</code>.
     */
    public final TableField<PointsOfCallRecord, Integer> WIDE = createField("wide", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>handycapper.points_of_call</code> table reference
     */
    public PointsOfCall() {
        this(DSL.name("points_of_call"), null);
    }

    /**
     * Create an aliased <code>handycapper.points_of_call</code> table reference
     */
    public PointsOfCall(String alias) {
        this(DSL.name(alias), POINTS_OF_CALL);
    }

    /**
     * Create an aliased <code>handycapper.points_of_call</code> table reference
     */
    public PointsOfCall(Name alias) {
        this(alias, POINTS_OF_CALL);
    }

    private PointsOfCall(Name alias, Table<PointsOfCallRecord> aliased) {
        this(alias, aliased, null);
    }

    private PointsOfCall(Name alias, Table<PointsOfCallRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PointsOfCallRecord, Integer> getIdentity() {
        return Keys.IDENTITY_POINTS_OF_CALL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCall as(String alias) {
        return new PointsOfCall(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCall as(Name alias) {
        return new PointsOfCall(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PointsOfCall rename(String name) {
        return new PointsOfCall(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PointsOfCall rename(Name name) {
        return new PointsOfCall(name, null);
    }
}
