/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.RacesRecord;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Races extends TableImpl<RacesRecord> {

    private static final long serialVersionUID = 804636125;

    /**
     * The reference instance of <code>handycapper.races</code>
     */
    public static final Races RACES = new Races();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RacesRecord> getRecordType() {
        return RacesRecord.class;
    }

    /**
     * The column <code>handycapper.races.id</code>.
     */
    public final TableField<RacesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('races_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.races.date</code>.
     */
    public final TableField<RacesRecord, Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>handycapper.races.track</code>.
     */
    public final TableField<RacesRecord, String> TRACK = createField("track", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>handycapper.races.track_canonical</code>.
     */
    public final TableField<RacesRecord, String> TRACK_CANONICAL = createField("track_canonical", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>handycapper.races.track_state</code>.
     */
    public final TableField<RacesRecord, String> TRACK_STATE = createField("track_state", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>handycapper.races.track_country</code>.
     */
    public final TableField<RacesRecord, String> TRACK_COUNTRY = createField("track_country", org.jooq.impl.SQLDataType.VARCHAR(3).nullable(false), this, "");

    /**
     * The column <code>handycapper.races.track_name</code>.
     */
    public final TableField<RacesRecord, String> TRACK_NAME = createField("track_name", org.jooq.impl.SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>handycapper.races.number</code>.
     */
    public final TableField<RacesRecord, Integer> NUMBER = createField("number", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.breed</code>.
     */
    public final TableField<RacesRecord, String> BREED = createField("breed", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.races.type</code>.
     */
    public final TableField<RacesRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(75), this, "");

    /**
     * The column <code>handycapper.races.code</code>.
     */
    public final TableField<RacesRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>handycapper.races.race_name</code>.
     */
    public final TableField<RacesRecord, String> RACE_NAME = createField("race_name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.races.grade</code>.
     */
    public final TableField<RacesRecord, Integer> GRADE = createField("grade", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.black_type</code>.
     */
    public final TableField<RacesRecord, String> BLACK_TYPE = createField("black_type", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.races.conditions</code>.
     */
    public final TableField<RacesRecord, String> CONDITIONS = createField("conditions", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>handycapper.races.min_claim</code>.
     */
    public final TableField<RacesRecord, Integer> MIN_CLAIM = createField("min_claim", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.max_claim</code>.
     */
    public final TableField<RacesRecord, Integer> MAX_CLAIM = createField("max_claim", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.restrictions</code>.
     */
    public final TableField<RacesRecord, String> RESTRICTIONS = createField("restrictions", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.races.min_age</code>.
     */
    public final TableField<RacesRecord, Integer> MIN_AGE = createField("min_age", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.max_age</code>.
     */
    public final TableField<RacesRecord, Integer> MAX_AGE = createField("max_age", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.age_code</code>.
     */
    public final TableField<RacesRecord, String> AGE_CODE = createField("age_code", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.races.sexes</code>.
     */
    public final TableField<RacesRecord, Integer> SEXES = createField("sexes", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.sexes_code</code>.
     */
    public final TableField<RacesRecord, String> SEXES_CODE = createField("sexes_code", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.races.female_only</code>.
     */
    public final TableField<RacesRecord, Boolean> FEMALE_ONLY = createField("female_only", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.races.state_bred</code>.
     */
    public final TableField<RacesRecord, Boolean> STATE_BRED = createField("state_bred", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.races.distance_text</code>.
     */
    public final TableField<RacesRecord, String> DISTANCE_TEXT = createField("distance_text", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.races.distance_compact</code>.
     */
    public final TableField<RacesRecord, String> DISTANCE_COMPACT = createField("distance_compact", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.races.feet</code>.
     */
    public final TableField<RacesRecord, Integer> FEET = createField("feet", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.furlongs</code>.
     */
    public final TableField<RacesRecord, Double> FURLONGS = createField("furlongs", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.races.exact</code>.
     */
    public final TableField<RacesRecord, Boolean> EXACT = createField("exact", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.races.run_up</code>.
     */
    public final TableField<RacesRecord, Integer> RUN_UP = createField("run_up", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.temp_rail</code>.
     */
    public final TableField<RacesRecord, Integer> TEMP_RAIL = createField("temp_rail", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.surface</code>.
     */
    public final TableField<RacesRecord, String> SURFACE = createField("surface", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.races.course</code>.
     */
    public final TableField<RacesRecord, String> COURSE = createField("course", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.races.track_condition</code>.
     */
    public final TableField<RacesRecord, String> TRACK_CONDITION = createField("track_condition", org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>handycapper.races.scheduled_surface</code>.
     */
    public final TableField<RacesRecord, String> SCHEDULED_SURFACE = createField("scheduled_surface", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.races.scheduled_course</code>.
     */
    public final TableField<RacesRecord, String> SCHEDULED_COURSE = createField("scheduled_course", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.races.off_turf</code>.
     */
    public final TableField<RacesRecord, Boolean> OFF_TURF = createField("off_turf", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.races.format</code>.
     */
    public final TableField<RacesRecord, String> FORMAT = createField("format", org.jooq.impl.SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>handycapper.races.track_record_holder</code>.
     */
    public final TableField<RacesRecord, String> TRACK_RECORD_HOLDER = createField("track_record_holder", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>handycapper.races.track_record_time</code>.
     */
    public final TableField<RacesRecord, String> TRACK_RECORD_TIME = createField("track_record_time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.races.track_record_millis</code>.
     */
    public final TableField<RacesRecord, Long> TRACK_RECORD_MILLIS = createField("track_record_millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>handycapper.races.track_record_date</code>.
     */
    public final TableField<RacesRecord, Date> TRACK_RECORD_DATE = createField("track_record_date", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>handycapper.races.purse</code>.
     */
    public final TableField<RacesRecord, Integer> PURSE = createField("purse", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.purse_text</code>.
     */
    public final TableField<RacesRecord, String> PURSE_TEXT = createField("purse_text", org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>handycapper.races.available_money</code>.
     */
    public final TableField<RacesRecord, String> AVAILABLE_MONEY = createField("available_money", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.races.purse_enhancements</code>.
     */
    public final TableField<RacesRecord, String> PURSE_ENHANCEMENTS = createField("purse_enhancements", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>handycapper.races.value_of_race</code>.
     */
    public final TableField<RacesRecord, String> VALUE_OF_RACE = createField("value_of_race", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>handycapper.races.weather</code>.
     */
    public final TableField<RacesRecord, String> WEATHER = createField("weather", org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>handycapper.races.wind_speed</code>.
     */
    public final TableField<RacesRecord, Integer> WIND_SPEED = createField("wind_speed", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.wind_direction</code>.
     */
    public final TableField<RacesRecord, String> WIND_DIRECTION = createField("wind_direction", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.races.post_time</code>.
     */
    public final TableField<RacesRecord, String> POST_TIME = createField("post_time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.races.start_comments</code>.
     */
    public final TableField<RacesRecord, String> START_COMMENTS = createField("start_comments", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.races.timer</code>.
     */
    public final TableField<RacesRecord, String> TIMER = createField("timer", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.races.dead_heat</code>.
     */
    public final TableField<RacesRecord, Boolean> DEAD_HEAT = createField("dead_heat", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.races.number_of_runners</code>.
     */
    public final TableField<RacesRecord, Integer> NUMBER_OF_RUNNERS = createField("number_of_runners", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.final_time</code>.
     */
    public final TableField<RacesRecord, String> FINAL_TIME = createField("final_time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.races.final_millis</code>.
     */
    public final TableField<RacesRecord, Long> FINAL_MILLIS = createField("final_millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>handycapper.races.total_wps_pool</code>.
     */
    public final TableField<RacesRecord, Integer> TOTAL_WPS_POOL = createField("total_wps_pool", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.races.footnotes</code>.
     */
    public final TableField<RacesRecord, String> FOOTNOTES = createField("footnotes", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>handycapper.races</code> table reference
     */
    public Races() {
        this(DSL.name("races"), null);
    }

    /**
     * Create an aliased <code>handycapper.races</code> table reference
     */
    public Races(String alias) {
        this(DSL.name(alias), RACES);
    }

    /**
     * Create an aliased <code>handycapper.races</code> table reference
     */
    public Races(Name alias) {
        this(alias, RACES);
    }

    private Races(Name alias, Table<RacesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Races(Name alias, Table<RacesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RacesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RACES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Races as(String alias) {
        return new Races(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Races as(Name alias) {
        return new Races(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Races rename(String name) {
        return new Races(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Races rename(Name name) {
        return new Races(name, null);
    }
}
