/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.RatingsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ratings extends TableImpl<RatingsRecord> {

    private static final long serialVersionUID = -1550270803;

    /**
     * The reference instance of <code>handycapper.ratings</code>
     */
    public static final Ratings RATINGS = new Ratings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RatingsRecord> getRecordType() {
        return RatingsRecord.class;
    }

    /**
     * The column <code>handycapper.ratings.id</code>.
     */
    public final TableField<RatingsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('ratings_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.ratings.race_id</code>.
     */
    public final TableField<RatingsRecord, Integer> RACE_ID = createField("race_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.ratings.name</code>.
     */
    public final TableField<RatingsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.ratings.text</code>.
     */
    public final TableField<RatingsRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.ratings.value</code>.
     */
    public final TableField<RatingsRecord, Double> VALUE = createField("value", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.ratings.extra</code>.
     */
    public final TableField<RatingsRecord, String> EXTRA = createField("extra", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * Create a <code>handycapper.ratings</code> table reference
     */
    public Ratings() {
        this(DSL.name("ratings"), null);
    }

    /**
     * Create an aliased <code>handycapper.ratings</code> table reference
     */
    public Ratings(String alias) {
        this(DSL.name(alias), RATINGS);
    }

    /**
     * Create an aliased <code>handycapper.ratings</code> table reference
     */
    public Ratings(Name alias) {
        this(alias, RATINGS);
    }

    private Ratings(Name alias, Table<RatingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ratings(Name alias, Table<RatingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RatingsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RATINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ratings as(String alias) {
        return new Ratings(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Ratings as(Name alias) {
        return new Ratings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ratings rename(String name) {
        return new Ratings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ratings rename(Name name) {
        return new Ratings(name, null);
    }
}
