/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.ScratchesRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scratches extends TableImpl<ScratchesRecord> {

    private static final long serialVersionUID = -529414123;

    /**
     * The reference instance of <code>handycapper.scratches</code>
     */
    public static final Scratches SCRATCHES = new Scratches();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScratchesRecord> getRecordType() {
        return ScratchesRecord.class;
    }

    /**
     * The column <code>handycapper.scratches.id</code>.
     */
    public final TableField<ScratchesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('scratches_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.scratches.race_id</code>.
     */
    public final TableField<ScratchesRecord, Integer> RACE_ID = createField("race_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.scratches.horse</code>.
     */
    public final TableField<ScratchesRecord, String> HORSE = createField("horse", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>handycapper.scratches.reason</code>.
     */
    public final TableField<ScratchesRecord, String> REASON = createField("reason", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * Create a <code>handycapper.scratches</code> table reference
     */
    public Scratches() {
        this(DSL.name("scratches"), null);
    }

    /**
     * Create an aliased <code>handycapper.scratches</code> table reference
     */
    public Scratches(String alias) {
        this(DSL.name(alias), SCRATCHES);
    }

    /**
     * Create an aliased <code>handycapper.scratches</code> table reference
     */
    public Scratches(Name alias) {
        this(alias, SCRATCHES);
    }

    private Scratches(Name alias, Table<ScratchesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Scratches(Name alias, Table<ScratchesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ScratchesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SCRATCHES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Scratches as(String alias) {
        return new Scratches(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Scratches as(Name alias) {
        return new Scratches(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Scratches rename(String name) {
        return new Scratches(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Scratches rename(Name name) {
        return new Scratches(name, null);
    }
}
