/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.SplitsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Splits extends TableImpl<SplitsRecord> {

    private static final long serialVersionUID = 1276858515;

    /**
     * The reference instance of <code>handycapper.splits</code>
     */
    public static final Splits SPLITS = new Splits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SplitsRecord> getRecordType() {
        return SplitsRecord.class;
    }

    /**
     * The column <code>handycapper.splits.id</code>.
     */
    public final TableField<SplitsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('splits_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.splits.race_id</code>.
     */
    public final TableField<SplitsRecord, Integer> RACE_ID = createField("race_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.splits.point</code>.
     */
    public final TableField<SplitsRecord, Integer> POINT = createField("point", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.splits.text</code>.
     */
    public final TableField<SplitsRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.VARCHAR(25).nullable(false), this, "");

    /**
     * The column <code>handycapper.splits.compact</code>.
     */
    public final TableField<SplitsRecord, String> COMPACT = createField("compact", org.jooq.impl.SQLDataType.VARCHAR(35).nullable(false), this, "");

    /**
     * The column <code>handycapper.splits.feet</code>.
     */
    public final TableField<SplitsRecord, Integer> FEET = createField("feet", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.splits.furlongs</code>.
     */
    public final TableField<SplitsRecord, Double> FURLONGS = createField("furlongs", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>handycapper.splits.time</code>.
     */
    public final TableField<SplitsRecord, String> TIME = createField("time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.splits.millis</code>.
     */
    public final TableField<SplitsRecord, Long> MILLIS = createField("millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>handycapper.splits.from_point</code>.
     */
    public final TableField<SplitsRecord, Integer> FROM_POINT = createField("from_point", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.splits.from_text</code>.
     */
    public final TableField<SplitsRecord, String> FROM_TEXT = createField("from_text", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.splits.from_compact</code>.
     */
    public final TableField<SplitsRecord, String> FROM_COMPACT = createField("from_compact", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.splits.from_feet</code>.
     */
    public final TableField<SplitsRecord, Integer> FROM_FEET = createField("from_feet", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.splits.from_furlongs</code>.
     */
    public final TableField<SplitsRecord, Double> FROM_FURLONGS = createField("from_furlongs", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.splits.from_time</code>.
     */
    public final TableField<SplitsRecord, String> FROM_TIME = createField("from_time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.splits.from_millis</code>.
     */
    public final TableField<SplitsRecord, Long> FROM_MILLIS = createField("from_millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>handycapper.splits.to_point</code>.
     */
    public final TableField<SplitsRecord, Integer> TO_POINT = createField("to_point", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.splits.to_text</code>.
     */
    public final TableField<SplitsRecord, String> TO_TEXT = createField("to_text", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.splits.to_compact</code>.
     */
    public final TableField<SplitsRecord, String> TO_COMPACT = createField("to_compact", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.splits.to_feet</code>.
     */
    public final TableField<SplitsRecord, Integer> TO_FEET = createField("to_feet", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.splits.to_furlongs</code>.
     */
    public final TableField<SplitsRecord, Double> TO_FURLONGS = createField("to_furlongs", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.splits.to_time</code>.
     */
    public final TableField<SplitsRecord, String> TO_TIME = createField("to_time", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.splits.to_millis</code>.
     */
    public final TableField<SplitsRecord, Long> TO_MILLIS = createField("to_millis", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>handycapper.splits</code> table reference
     */
    public Splits() {
        this(DSL.name("splits"), null);
    }

    /**
     * Create an aliased <code>handycapper.splits</code> table reference
     */
    public Splits(String alias) {
        this(DSL.name(alias), SPLITS);
    }

    /**
     * Create an aliased <code>handycapper.splits</code> table reference
     */
    public Splits(Name alias) {
        this(alias, SPLITS);
    }

    private Splits(Name alias, Table<SplitsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Splits(Name alias, Table<SplitsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SplitsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SPLITS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Splits as(String alias) {
        return new Splits(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Splits as(Name alias) {
        return new Splits(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Splits rename(String name) {
        return new Splits(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Splits rename(Name name) {
        return new Splits(name, null);
    }
}
