/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.StartersRecord;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Starters extends TableImpl<StartersRecord> {

    private static final long serialVersionUID = -1146378571;

    /**
     * The reference instance of <code>handycapper.starters</code>
     */
    public static final Starters STARTERS = new Starters();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StartersRecord> getRecordType() {
        return StartersRecord.class;
    }

    /**
     * The column <code>handycapper.starters.id</code>.
     */
    public final TableField<StartersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('starters_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.starters.race_id</code>.
     */
    public final TableField<StartersRecord, Integer> RACE_ID = createField("race_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.starters.last_raced_date</code>.
     */
    public final TableField<StartersRecord, Date> LAST_RACED_DATE = createField("last_raced_date", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>handycapper.starters.last_raced_days_since</code>.
     */
    public final TableField<StartersRecord, Integer> LAST_RACED_DAYS_SINCE = createField("last_raced_days_since", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.last_raced_track</code>.
     */
    public final TableField<StartersRecord, String> LAST_RACED_TRACK = createField("last_raced_track", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>handycapper.starters.last_raced_track_canonical</code>.
     */
    public final TableField<StartersRecord, String> LAST_RACED_TRACK_CANONICAL = createField("last_raced_track_canonical", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>handycapper.starters.last_raced_track_state</code>.
     */
    public final TableField<StartersRecord, String> LAST_RACED_TRACK_STATE = createField("last_raced_track_state", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>handycapper.starters.last_raced_track_country</code>.
     */
    public final TableField<StartersRecord, String> LAST_RACED_TRACK_COUNTRY = createField("last_raced_track_country", org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>handycapper.starters.last_raced_track_name</code>.
     */
    public final TableField<StartersRecord, String> LAST_RACED_TRACK_NAME = createField("last_raced_track_name", org.jooq.impl.SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>handycapper.starters.last_raced_number</code>.
     */
    public final TableField<StartersRecord, Integer> LAST_RACED_NUMBER = createField("last_raced_number", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.last_raced_position</code>.
     */
    public final TableField<StartersRecord, Integer> LAST_RACED_POSITION = createField("last_raced_position", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.program</code>.
     */
    public final TableField<StartersRecord, String> PROGRAM = createField("program", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.starters.entry</code>.
     */
    public final TableField<StartersRecord, Boolean> ENTRY = createField("entry", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.starters.entry_program</code>.
     */
    public final TableField<StartersRecord, String> ENTRY_PROGRAM = createField("entry_program", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.starters.horse</code>.
     */
    public final TableField<StartersRecord, String> HORSE = createField("horse", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>handycapper.starters.jockey_first</code>.
     */
    public final TableField<StartersRecord, String> JOCKEY_FIRST = createField("jockey_first", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.starters.jockey_last</code>.
     */
    public final TableField<StartersRecord, String> JOCKEY_LAST = createField("jockey_last", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.starters.trainer_first</code>.
     */
    public final TableField<StartersRecord, String> TRAINER_FIRST = createField("trainer_first", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.starters.trainer_last</code>.
     */
    public final TableField<StartersRecord, String> TRAINER_LAST = createField("trainer_last", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.starters.owner</code>.
     */
    public final TableField<StartersRecord, String> OWNER = createField("owner", org.jooq.impl.SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>handycapper.starters.weight</code>.
     */
    public final TableField<StartersRecord, Integer> WEIGHT = createField("weight", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.jockey_allowance</code>.
     */
    public final TableField<StartersRecord, Integer> JOCKEY_ALLOWANCE = createField("jockey_allowance", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.medication_equipment</code>.
     */
    public final TableField<StartersRecord, String> MEDICATION_EQUIPMENT = createField("medication_equipment", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>handycapper.starters.claim_price</code>.
     */
    public final TableField<StartersRecord, Integer> CLAIM_PRICE = createField("claim_price", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.claimed</code>.
     */
    public final TableField<StartersRecord, Boolean> CLAIMED = createField("claimed", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.starters.new_trainer_name</code>.
     */
    public final TableField<StartersRecord, String> NEW_TRAINER_NAME = createField("new_trainer_name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.starters.new_owner_name</code>.
     */
    public final TableField<StartersRecord, String> NEW_OWNER_NAME = createField("new_owner_name", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>handycapper.starters.pp</code>.
     */
    public final TableField<StartersRecord, Integer> PP = createField("pp", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.finish_position</code>.
     */
    public final TableField<StartersRecord, Integer> FINISH_POSITION = createField("finish_position", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.official_position</code>.
     */
    public final TableField<StartersRecord, Integer> OFFICIAL_POSITION = createField("official_position", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.position_dead_heat</code>.
     */
    public final TableField<StartersRecord, Boolean> POSITION_DEAD_HEAT = createField("position_dead_heat", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.starters.wagering_position</code>.
     */
    public final TableField<StartersRecord, Integer> WAGERING_POSITION = createField("wagering_position", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.winner</code>.
     */
    public final TableField<StartersRecord, Boolean> WINNER = createField("winner", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.starters.disqualified</code>.
     */
    public final TableField<StartersRecord, Boolean> DISQUALIFIED = createField("disqualified", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.starters.odds</code>.
     */
    public final TableField<StartersRecord, Double> ODDS = createField("odds", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.starters.choice</code>.
     */
    public final TableField<StartersRecord, Integer> CHOICE = createField("choice", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>handycapper.starters.favorite</code>.
     */
    public final TableField<StartersRecord, Boolean> FAVORITE = createField("favorite", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>handycapper.starters.comments</code>.
     */
    public final TableField<StartersRecord, String> COMMENTS = createField("comments", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>handycapper.starters</code> table reference
     */
    public Starters() {
        this(DSL.name("starters"), null);
    }

    /**
     * Create an aliased <code>handycapper.starters</code> table reference
     */
    public Starters(String alias) {
        this(DSL.name(alias), STARTERS);
    }

    /**
     * Create an aliased <code>handycapper.starters</code> table reference
     */
    public Starters(Name alias) {
        this(alias, STARTERS);
    }

    private Starters(Name alias, Table<StartersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Starters(Name alias, Table<StartersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StartersRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STARTERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Starters as(String alias) {
        return new Starters(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Starters as(Name alias) {
        return new Starters(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Starters rename(String name) {
        return new Starters(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Starters rename(Name name) {
        return new Starters(name, null);
    }
}
