/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables;


import com.robinhowlett.handycapper.domain.Handycapper;
import com.robinhowlett.handycapper.domain.Keys;
import com.robinhowlett.handycapper.domain.tables.records.WpsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wps extends TableImpl<WpsRecord> {

    private static final long serialVersionUID = -519650124;

    /**
     * The reference instance of <code>handycapper.wps</code>
     */
    public static final Wps WPS = new Wps();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WpsRecord> getRecordType() {
        return WpsRecord.class;
    }

    /**
     * The column <code>handycapper.wps.id</code>.
     */
    public final TableField<WpsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('wps_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>handycapper.wps.starter_id</code>.
     */
    public final TableField<WpsRecord, Integer> STARTER_ID = createField("starter_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>handycapper.wps.type</code>.
     */
    public final TableField<WpsRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>handycapper.wps.unit</code>.
     */
    public final TableField<WpsRecord, Double> UNIT = createField("unit", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.wps.payoff</code>.
     */
    public final TableField<WpsRecord, Double> PAYOFF = createField("payoff", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>handycapper.wps.odds</code>.
     */
    public final TableField<WpsRecord, Double> ODDS = createField("odds", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>handycapper.wps</code> table reference
     */
    public Wps() {
        this(DSL.name("wps"), null);
    }

    /**
     * Create an aliased <code>handycapper.wps</code> table reference
     */
    public Wps(String alias) {
        this(DSL.name(alias), WPS);
    }

    /**
     * Create an aliased <code>handycapper.wps</code> table reference
     */
    public Wps(Name alias) {
        this(alias, WPS);
    }

    private Wps(Name alias, Table<WpsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Wps(Name alias, Table<WpsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Handycapper.HANDYCAPPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WpsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_WPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Wps as(String alias) {
        return new Wps(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Wps as(Name alias) {
        return new Wps(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Wps rename(String name) {
        return new Wps(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Wps rename(Name name) {
        return new Wps(name, null);
    }
}
