/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain;


import com.robinhowlett.handycapper.domain.tables.Breeding;
import com.robinhowlett.handycapper.domain.tables.Cancelled;
import com.robinhowlett.handycapper.domain.tables.Equip;
import com.robinhowlett.handycapper.domain.tables.Exotics;
import com.robinhowlett.handycapper.domain.tables.Fractionals;
import com.robinhowlett.handycapper.domain.tables.IndivFractionals;
import com.robinhowlett.handycapper.domain.tables.IndivRatings;
import com.robinhowlett.handycapper.domain.tables.IndivSplits;
import com.robinhowlett.handycapper.domain.tables.Meds;
import com.robinhowlett.handycapper.domain.tables.PointsOfCall;
import com.robinhowlett.handycapper.domain.tables.Races;
import com.robinhowlett.handycapper.domain.tables.Ratings;
import com.robinhowlett.handycapper.domain.tables.Scratches;
import com.robinhowlett.handycapper.domain.tables.Splits;
import com.robinhowlett.handycapper.domain.tables.Starters;
import com.robinhowlett.handycapper.domain.tables.Wps;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Handycapper extends SchemaImpl {

    private static final long serialVersionUID = 2141520345;

    /**
     * The reference instance of <code>handycapper</code>
     */
    public static final Handycapper HANDYCAPPER = new Handycapper();

    /**
     * The table <code>handycapper.breeding</code>.
     */
    public final Breeding BREEDING = com.robinhowlett.handycapper.domain.tables.Breeding.BREEDING;

    /**
     * The table <code>handycapper.cancelled</code>.
     */
    public final Cancelled CANCELLED = com.robinhowlett.handycapper.domain.tables.Cancelled.CANCELLED;

    /**
     * The table <code>handycapper.equip</code>.
     */
    public final Equip EQUIP = com.robinhowlett.handycapper.domain.tables.Equip.EQUIP;

    /**
     * The table <code>handycapper.exotics</code>.
     */
    public final Exotics EXOTICS = com.robinhowlett.handycapper.domain.tables.Exotics.EXOTICS;

    /**
     * The table <code>handycapper.fractionals</code>.
     */
    public final Fractionals FRACTIONALS = com.robinhowlett.handycapper.domain.tables.Fractionals.FRACTIONALS;

    /**
     * The table <code>handycapper.indiv_fractionals</code>.
     */
    public final IndivFractionals INDIV_FRACTIONALS = com.robinhowlett.handycapper.domain.tables.IndivFractionals.INDIV_FRACTIONALS;

    /**
     * The table <code>handycapper.indiv_ratings</code>.
     */
    public final IndivRatings INDIV_RATINGS = com.robinhowlett.handycapper.domain.tables.IndivRatings.INDIV_RATINGS;

    /**
     * The table <code>handycapper.indiv_splits</code>.
     */
    public final IndivSplits INDIV_SPLITS = com.robinhowlett.handycapper.domain.tables.IndivSplits.INDIV_SPLITS;

    /**
     * The table <code>handycapper.meds</code>.
     */
    public final Meds MEDS = com.robinhowlett.handycapper.domain.tables.Meds.MEDS;

    /**
     * The table <code>handycapper.points_of_call</code>.
     */
    public final PointsOfCall POINTS_OF_CALL = com.robinhowlett.handycapper.domain.tables.PointsOfCall.POINTS_OF_CALL;

    /**
     * The table <code>handycapper.races</code>.
     */
    public final Races RACES = com.robinhowlett.handycapper.domain.tables.Races.RACES;

    /**
     * The table <code>handycapper.ratings</code>.
     */
    public final Ratings RATINGS = com.robinhowlett.handycapper.domain.tables.Ratings.RATINGS;

    /**
     * The table <code>handycapper.scratches</code>.
     */
    public final Scratches SCRATCHES = com.robinhowlett.handycapper.domain.tables.Scratches.SCRATCHES;

    /**
     * The table <code>handycapper.splits</code>.
     */
    public final Splits SPLITS = com.robinhowlett.handycapper.domain.tables.Splits.SPLITS;

    /**
     * The table <code>handycapper.starters</code>.
     */
    public final Starters STARTERS = com.robinhowlett.handycapper.domain.tables.Starters.STARTERS;

    /**
     * The table <code>handycapper.wps</code>.
     */
    public final Wps WPS = com.robinhowlett.handycapper.domain.tables.Wps.WPS;

    /**
     * No further instances allowed
     */
    private Handycapper() {
        super("handycapper", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.BREEDING_ID_SEQ,
            Sequences.CANCELLED_ID_SEQ,
            Sequences.EQUIP_ID_SEQ,
            Sequences.EXOTICS_ID_SEQ,
            Sequences.FRACTIONALS_ID_SEQ,
            Sequences.INDIV_FRACTIONALS_ID_SEQ,
            Sequences.INDIV_RATINGS_ID_SEQ,
            Sequences.INDIV_SPLITS_ID_SEQ,
            Sequences.MEDS_ID_SEQ,
            Sequences.POINTS_OF_CALL_ID_SEQ,
            Sequences.RACES_ID_SEQ,
            Sequences.RATINGS_ID_SEQ,
            Sequences.SCRATCHES_ID_SEQ,
            Sequences.SPLITS_ID_SEQ,
            Sequences.STARTERS_ID_SEQ,
            Sequences.WPS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Breeding.BREEDING,
            Cancelled.CANCELLED,
            Equip.EQUIP,
            Exotics.EXOTICS,
            Fractionals.FRACTIONALS,
            IndivFractionals.INDIV_FRACTIONALS,
            IndivRatings.INDIV_RATINGS,
            IndivSplits.INDIV_SPLITS,
            Meds.MEDS,
            PointsOfCall.POINTS_OF_CALL,
            Races.RACES,
            Ratings.RATINGS,
            Scratches.SCRATCHES,
            Splits.SPLITS,
            Starters.STARTERS,
            Wps.WPS);
    }
}
