/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain;


import com.robinhowlett.handycapper.domain.tables.Breeding;
import com.robinhowlett.handycapper.domain.tables.Cancelled;
import com.robinhowlett.handycapper.domain.tables.Equip;
import com.robinhowlett.handycapper.domain.tables.Exotics;
import com.robinhowlett.handycapper.domain.tables.Fractionals;
import com.robinhowlett.handycapper.domain.tables.IndivFractionals;
import com.robinhowlett.handycapper.domain.tables.IndivRatings;
import com.robinhowlett.handycapper.domain.tables.IndivSplits;
import com.robinhowlett.handycapper.domain.tables.Meds;
import com.robinhowlett.handycapper.domain.tables.PointsOfCall;
import com.robinhowlett.handycapper.domain.tables.Races;
import com.robinhowlett.handycapper.domain.tables.Ratings;
import com.robinhowlett.handycapper.domain.tables.Scratches;
import com.robinhowlett.handycapper.domain.tables.Splits;
import com.robinhowlett.handycapper.domain.tables.Starters;
import com.robinhowlett.handycapper.domain.tables.Wps;
import com.robinhowlett.handycapper.domain.tables.records.BreedingRecord;
import com.robinhowlett.handycapper.domain.tables.records.CancelledRecord;
import com.robinhowlett.handycapper.domain.tables.records.EquipRecord;
import com.robinhowlett.handycapper.domain.tables.records.ExoticsRecord;
import com.robinhowlett.handycapper.domain.tables.records.FractionalsRecord;
import com.robinhowlett.handycapper.domain.tables.records.IndivFractionalsRecord;
import com.robinhowlett.handycapper.domain.tables.records.IndivRatingsRecord;
import com.robinhowlett.handycapper.domain.tables.records.IndivSplitsRecord;
import com.robinhowlett.handycapper.domain.tables.records.MedsRecord;
import com.robinhowlett.handycapper.domain.tables.records.PointsOfCallRecord;
import com.robinhowlett.handycapper.domain.tables.records.RacesRecord;
import com.robinhowlett.handycapper.domain.tables.records.RatingsRecord;
import com.robinhowlett.handycapper.domain.tables.records.ScratchesRecord;
import com.robinhowlett.handycapper.domain.tables.records.SplitsRecord;
import com.robinhowlett.handycapper.domain.tables.records.StartersRecord;
import com.robinhowlett.handycapper.domain.tables.records.WpsRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>handycapper</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BreedingRecord, Integer> IDENTITY_BREEDING = Identities0.IDENTITY_BREEDING;
    public static final Identity<CancelledRecord, Integer> IDENTITY_CANCELLED = Identities0.IDENTITY_CANCELLED;
    public static final Identity<EquipRecord, Integer> IDENTITY_EQUIP = Identities0.IDENTITY_EQUIP;
    public static final Identity<ExoticsRecord, Integer> IDENTITY_EXOTICS = Identities0.IDENTITY_EXOTICS;
    public static final Identity<FractionalsRecord, Integer> IDENTITY_FRACTIONALS = Identities0.IDENTITY_FRACTIONALS;
    public static final Identity<IndivFractionalsRecord, Integer> IDENTITY_INDIV_FRACTIONALS = Identities0.IDENTITY_INDIV_FRACTIONALS;
    public static final Identity<IndivRatingsRecord, Integer> IDENTITY_INDIV_RATINGS = Identities0.IDENTITY_INDIV_RATINGS;
    public static final Identity<IndivSplitsRecord, Integer> IDENTITY_INDIV_SPLITS = Identities0.IDENTITY_INDIV_SPLITS;
    public static final Identity<MedsRecord, Integer> IDENTITY_MEDS = Identities0.IDENTITY_MEDS;
    public static final Identity<PointsOfCallRecord, Integer> IDENTITY_POINTS_OF_CALL = Identities0.IDENTITY_POINTS_OF_CALL;
    public static final Identity<RacesRecord, Integer> IDENTITY_RACES = Identities0.IDENTITY_RACES;
    public static final Identity<RatingsRecord, Integer> IDENTITY_RATINGS = Identities0.IDENTITY_RATINGS;
    public static final Identity<ScratchesRecord, Integer> IDENTITY_SCRATCHES = Identities0.IDENTITY_SCRATCHES;
    public static final Identity<SplitsRecord, Integer> IDENTITY_SPLITS = Identities0.IDENTITY_SPLITS;
    public static final Identity<StartersRecord, Integer> IDENTITY_STARTERS = Identities0.IDENTITY_STARTERS;
    public static final Identity<WpsRecord, Integer> IDENTITY_WPS = Identities0.IDENTITY_WPS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<BreedingRecord, Integer> IDENTITY_BREEDING = Internal.createIdentity(Breeding.BREEDING, Breeding.BREEDING.ID);
        public static Identity<CancelledRecord, Integer> IDENTITY_CANCELLED = Internal.createIdentity(Cancelled.CANCELLED, Cancelled.CANCELLED.ID);
        public static Identity<EquipRecord, Integer> IDENTITY_EQUIP = Internal.createIdentity(Equip.EQUIP, Equip.EQUIP.ID);
        public static Identity<ExoticsRecord, Integer> IDENTITY_EXOTICS = Internal.createIdentity(Exotics.EXOTICS, Exotics.EXOTICS.ID);
        public static Identity<FractionalsRecord, Integer> IDENTITY_FRACTIONALS = Internal.createIdentity(Fractionals.FRACTIONALS, Fractionals.FRACTIONALS.ID);
        public static Identity<IndivFractionalsRecord, Integer> IDENTITY_INDIV_FRACTIONALS = Internal.createIdentity(IndivFractionals.INDIV_FRACTIONALS, IndivFractionals.INDIV_FRACTIONALS.ID);
        public static Identity<IndivRatingsRecord, Integer> IDENTITY_INDIV_RATINGS = Internal.createIdentity(IndivRatings.INDIV_RATINGS, IndivRatings.INDIV_RATINGS.ID);
        public static Identity<IndivSplitsRecord, Integer> IDENTITY_INDIV_SPLITS = Internal.createIdentity(IndivSplits.INDIV_SPLITS, IndivSplits.INDIV_SPLITS.ID);
        public static Identity<MedsRecord, Integer> IDENTITY_MEDS = Internal.createIdentity(Meds.MEDS, Meds.MEDS.ID);
        public static Identity<PointsOfCallRecord, Integer> IDENTITY_POINTS_OF_CALL = Internal.createIdentity(PointsOfCall.POINTS_OF_CALL, PointsOfCall.POINTS_OF_CALL.ID);
        public static Identity<RacesRecord, Integer> IDENTITY_RACES = Internal.createIdentity(Races.RACES, Races.RACES.ID);
        public static Identity<RatingsRecord, Integer> IDENTITY_RATINGS = Internal.createIdentity(Ratings.RATINGS, Ratings.RATINGS.ID);
        public static Identity<ScratchesRecord, Integer> IDENTITY_SCRATCHES = Internal.createIdentity(Scratches.SCRATCHES, Scratches.SCRATCHES.ID);
        public static Identity<SplitsRecord, Integer> IDENTITY_SPLITS = Internal.createIdentity(Splits.SPLITS, Splits.SPLITS.ID);
        public static Identity<StartersRecord, Integer> IDENTITY_STARTERS = Internal.createIdentity(Starters.STARTERS, Starters.STARTERS.ID);
        public static Identity<WpsRecord, Integer> IDENTITY_WPS = Internal.createIdentity(Wps.WPS, Wps.WPS.ID);
    }
}
