/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in handycapper
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>handycapper.breeding_id_seq</code>
     */
    public static final Sequence<Long> BREEDING_ID_SEQ = new SequenceImpl<Long>("breeding_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.cancelled_id_seq</code>
     */
    public static final Sequence<Long> CANCELLED_ID_SEQ = new SequenceImpl<Long>("cancelled_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.equip_id_seq</code>
     */
    public static final Sequence<Long> EQUIP_ID_SEQ = new SequenceImpl<Long>("equip_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.exotics_id_seq</code>
     */
    public static final Sequence<Long> EXOTICS_ID_SEQ = new SequenceImpl<Long>("exotics_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.fractionals_id_seq</code>
     */
    public static final Sequence<Long> FRACTIONALS_ID_SEQ = new SequenceImpl<Long>("fractionals_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.indiv_fractionals_id_seq</code>
     */
    public static final Sequence<Long> INDIV_FRACTIONALS_ID_SEQ = new SequenceImpl<Long>("indiv_fractionals_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.indiv_ratings_id_seq</code>
     */
    public static final Sequence<Long> INDIV_RATINGS_ID_SEQ = new SequenceImpl<Long>("indiv_ratings_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.indiv_splits_id_seq</code>
     */
    public static final Sequence<Long> INDIV_SPLITS_ID_SEQ = new SequenceImpl<Long>("indiv_splits_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.meds_id_seq</code>
     */
    public static final Sequence<Long> MEDS_ID_SEQ = new SequenceImpl<Long>("meds_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.points_of_call_id_seq</code>
     */
    public static final Sequence<Long> POINTS_OF_CALL_ID_SEQ = new SequenceImpl<Long>("points_of_call_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.races_id_seq</code>
     */
    public static final Sequence<Long> RACES_ID_SEQ = new SequenceImpl<Long>("races_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.ratings_id_seq</code>
     */
    public static final Sequence<Long> RATINGS_ID_SEQ = new SequenceImpl<Long>("ratings_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.scratches_id_seq</code>
     */
    public static final Sequence<Long> SCRATCHES_ID_SEQ = new SequenceImpl<Long>("scratches_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.splits_id_seq</code>
     */
    public static final Sequence<Long> SPLITS_ID_SEQ = new SequenceImpl<Long>("splits_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.starters_id_seq</code>
     */
    public static final Sequence<Long> STARTERS_ID_SEQ = new SequenceImpl<Long>("starters_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>handycapper.wps_id_seq</code>
     */
    public static final Sequence<Long> WPS_ID_SEQ = new SequenceImpl<Long>("wps_id_seq", Handycapper.HANDYCAPPER, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
