/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain;


import com.robinhowlett.handycapper.domain.tables.Breeding;
import com.robinhowlett.handycapper.domain.tables.Cancelled;
import com.robinhowlett.handycapper.domain.tables.Equip;
import com.robinhowlett.handycapper.domain.tables.Exotics;
import com.robinhowlett.handycapper.domain.tables.Fractionals;
import com.robinhowlett.handycapper.domain.tables.IndivFractionals;
import com.robinhowlett.handycapper.domain.tables.IndivRatings;
import com.robinhowlett.handycapper.domain.tables.IndivSplits;
import com.robinhowlett.handycapper.domain.tables.Meds;
import com.robinhowlett.handycapper.domain.tables.PointsOfCall;
import com.robinhowlett.handycapper.domain.tables.Races;
import com.robinhowlett.handycapper.domain.tables.Ratings;
import com.robinhowlett.handycapper.domain.tables.Scratches;
import com.robinhowlett.handycapper.domain.tables.Splits;
import com.robinhowlett.handycapper.domain.tables.Starters;
import com.robinhowlett.handycapper.domain.tables.Wps;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in handycapper
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>handycapper.breeding</code>.
     */
    public static final Breeding BREEDING = com.robinhowlett.handycapper.domain.tables.Breeding.BREEDING;

    /**
     * The table <code>handycapper.cancelled</code>.
     */
    public static final Cancelled CANCELLED = com.robinhowlett.handycapper.domain.tables.Cancelled.CANCELLED;

    /**
     * The table <code>handycapper.equip</code>.
     */
    public static final Equip EQUIP = com.robinhowlett.handycapper.domain.tables.Equip.EQUIP;

    /**
     * The table <code>handycapper.exotics</code>.
     */
    public static final Exotics EXOTICS = com.robinhowlett.handycapper.domain.tables.Exotics.EXOTICS;

    /**
     * The table <code>handycapper.fractionals</code>.
     */
    public static final Fractionals FRACTIONALS = com.robinhowlett.handycapper.domain.tables.Fractionals.FRACTIONALS;

    /**
     * The table <code>handycapper.indiv_fractionals</code>.
     */
    public static final IndivFractionals INDIV_FRACTIONALS = com.robinhowlett.handycapper.domain.tables.IndivFractionals.INDIV_FRACTIONALS;

    /**
     * The table <code>handycapper.indiv_ratings</code>.
     */
    public static final IndivRatings INDIV_RATINGS = com.robinhowlett.handycapper.domain.tables.IndivRatings.INDIV_RATINGS;

    /**
     * The table <code>handycapper.indiv_splits</code>.
     */
    public static final IndivSplits INDIV_SPLITS = com.robinhowlett.handycapper.domain.tables.IndivSplits.INDIV_SPLITS;

    /**
     * The table <code>handycapper.meds</code>.
     */
    public static final Meds MEDS = com.robinhowlett.handycapper.domain.tables.Meds.MEDS;

    /**
     * The table <code>handycapper.points_of_call</code>.
     */
    public static final PointsOfCall POINTS_OF_CALL = com.robinhowlett.handycapper.domain.tables.PointsOfCall.POINTS_OF_CALL;

    /**
     * The table <code>handycapper.races</code>.
     */
    public static final Races RACES = com.robinhowlett.handycapper.domain.tables.Races.RACES;

    /**
     * The table <code>handycapper.ratings</code>.
     */
    public static final Ratings RATINGS = com.robinhowlett.handycapper.domain.tables.Ratings.RATINGS;

    /**
     * The table <code>handycapper.scratches</code>.
     */
    public static final Scratches SCRATCHES = com.robinhowlett.handycapper.domain.tables.Scratches.SCRATCHES;

    /**
     * The table <code>handycapper.splits</code>.
     */
    public static final Splits SPLITS = com.robinhowlett.handycapper.domain.tables.Splits.SPLITS;

    /**
     * The table <code>handycapper.starters</code>.
     */
    public static final Starters STARTERS = com.robinhowlett.handycapper.domain.tables.Starters.STARTERS;

    /**
     * The table <code>handycapper.wps</code>.
     */
    public static final Wps WPS = com.robinhowlett.handycapper.domain.tables.Wps.WPS;
}
