/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.Breeding;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BreedingRecord extends TableRecordImpl<BreedingRecord> implements Record11<Integer, Integer, String, String, String, String, String, String, Date, String, String> {

    private static final long serialVersionUID = 1088298179;

    /**
     * Setter for <code>handycapper.breeding.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.breeding.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.breeding.starter_id</code>.
     */
    public void setStarterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.breeding.starter_id</code>.
     */
    public Integer getStarterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>handycapper.breeding.horse</code>.
     */
    public void setHorse(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.breeding.horse</code>.
     */
    public String getHorse() {
        return (String) get(2);
    }

    /**
     * Setter for <code>handycapper.breeding.color</code>.
     */
    public void setColor(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.breeding.color</code>.
     */
    public String getColor() {
        return (String) get(3);
    }

    /**
     * Setter for <code>handycapper.breeding.sex</code>.
     */
    public void setSex(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.breeding.sex</code>.
     */
    public String getSex() {
        return (String) get(4);
    }

    /**
     * Setter for <code>handycapper.breeding.sire</code>.
     */
    public void setSire(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.breeding.sire</code>.
     */
    public String getSire() {
        return (String) get(5);
    }

    /**
     * Setter for <code>handycapper.breeding.dam</code>.
     */
    public void setDam(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>handycapper.breeding.dam</code>.
     */
    public String getDam() {
        return (String) get(6);
    }

    /**
     * Setter for <code>handycapper.breeding.dam_sire</code>.
     */
    public void setDamSire(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>handycapper.breeding.dam_sire</code>.
     */
    public String getDamSire() {
        return (String) get(7);
    }

    /**
     * Setter for <code>handycapper.breeding.foaling_date</code>.
     */
    public void setFoalingDate(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>handycapper.breeding.foaling_date</code>.
     */
    public Date getFoalingDate() {
        return (Date) get(8);
    }

    /**
     * Setter for <code>handycapper.breeding.foaling_location</code>.
     */
    public void setFoalingLocation(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>handycapper.breeding.foaling_location</code>.
     */
    public String getFoalingLocation() {
        return (String) get(9);
    }

    /**
     * Setter for <code>handycapper.breeding.breeder</code>.
     */
    public void setBreeder(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>handycapper.breeding.breeder</code>.
     */
    public String getBreeder() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, String, String, String, String, String, String, Date, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, String, String, String, String, String, String, Date, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Breeding.BREEDING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Breeding.BREEDING.STARTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Breeding.BREEDING.HORSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Breeding.BREEDING.COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Breeding.BREEDING.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Breeding.BREEDING.SIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Breeding.BREEDING.DAM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Breeding.BREEDING.DAM_SIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field9() {
        return Breeding.BREEDING.FOALING_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Breeding.BREEDING.FOALING_LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Breeding.BREEDING.BREEDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getStarterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getHorse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDam();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getDamSire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component9() {
        return getFoalingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getFoalingLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getBreeder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStarterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getHorse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDam();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDamSire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value9() {
        return getFoalingDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getFoalingLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getBreeder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value2(Integer value) {
        setStarterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value3(String value) {
        setHorse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value4(String value) {
        setColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value5(String value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value6(String value) {
        setSire(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value7(String value) {
        setDam(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value8(String value) {
        setDamSire(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value9(Date value) {
        setFoalingDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value10(String value) {
        setFoalingLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord value11(String value) {
        setBreeder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BreedingRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, String value7, String value8, Date value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BreedingRecord
     */
    public BreedingRecord() {
        super(Breeding.BREEDING);
    }

    /**
     * Create a detached, initialised BreedingRecord
     */
    public BreedingRecord(Integer id, Integer starterId, String horse, String color, String sex, String sire, String dam, String damSire, Date foalingDate, String foalingLocation, String breeder) {
        super(Breeding.BREEDING);

        set(0, id);
        set(1, starterId);
        set(2, horse);
        set(3, color);
        set(4, sex);
        set(5, sire);
        set(6, dam);
        set(7, damSire);
        set(8, foalingDate);
        set(9, foalingLocation);
        set(10, breeder);
    }
}
