/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.Cancelled;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CancelledRecord extends TableRecordImpl<CancelledRecord> implements Record9<Integer, String, Date, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1988318139;

    /**
     * Setter for <code>handycapper.cancelled.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.cancelled.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.cancelled.reason</code>.
     */
    public void setReason(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.cancelled.reason</code>.
     */
    public String getReason() {
        return (String) get(1);
    }

    /**
     * Setter for <code>handycapper.cancelled.date</code>.
     */
    public void setDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.cancelled.date</code>.
     */
    public Date getDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>handycapper.cancelled.track</code>.
     */
    public void setTrack(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.cancelled.track</code>.
     */
    public String getTrack() {
        return (String) get(3);
    }

    /**
     * Setter for <code>handycapper.cancelled.track_canonical</code>.
     */
    public void setTrackCanonical(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.cancelled.track_canonical</code>.
     */
    public String getTrackCanonical() {
        return (String) get(4);
    }

    /**
     * Setter for <code>handycapper.cancelled.track_state</code>.
     */
    public void setTrackState(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.cancelled.track_state</code>.
     */
    public String getTrackState() {
        return (String) get(5);
    }

    /**
     * Setter for <code>handycapper.cancelled.track_country</code>.
     */
    public void setTrackCountry(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>handycapper.cancelled.track_country</code>.
     */
    public String getTrackCountry() {
        return (String) get(6);
    }

    /**
     * Setter for <code>handycapper.cancelled.track_name</code>.
     */
    public void setTrackName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>handycapper.cancelled.track_name</code>.
     */
    public String getTrackName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>handycapper.cancelled.number</code>.
     */
    public void setNumber(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>handycapper.cancelled.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Date, String, String, String, String, String, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, Date, String, String, String, String, String, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Cancelled.CANCELLED.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cancelled.CANCELLED.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Cancelled.CANCELLED.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Cancelled.CANCELLED.TRACK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Cancelled.CANCELLED.TRACK_CANONICAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Cancelled.CANCELLED.TRACK_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Cancelled.CANCELLED.TRACK_COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Cancelled.CANCELLED.TRACK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Cancelled.CANCELLED.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getTrack();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTrackCanonical();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTrackState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTrackCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getTrackName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTrack();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTrackCanonical();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTrackState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTrackCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTrackName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord value2(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord value3(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord value4(String value) {
        setTrack(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord value5(String value) {
        setTrackCanonical(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord value6(String value) {
        setTrackState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord value7(String value) {
        setTrackCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord value8(String value) {
        setTrackName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord value9(Integer value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CancelledRecord values(Integer value1, String value2, Date value3, String value4, String value5, String value6, String value7, String value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CancelledRecord
     */
    public CancelledRecord() {
        super(Cancelled.CANCELLED);
    }

    /**
     * Create a detached, initialised CancelledRecord
     */
    public CancelledRecord(Integer id, String reason, Date date, String track, String trackCanonical, String trackState, String trackCountry, String trackName, Integer number) {
        super(Cancelled.CANCELLED);

        set(0, id);
        set(1, reason);
        set(2, date);
        set(3, track);
        set(4, trackCanonical);
        set(5, trackState);
        set(6, trackCountry);
        set(7, trackName);
        set(8, number);
    }
}
