/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.Exotics;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExoticsRecord extends TableRecordImpl<ExoticsRecord> implements Record10<Integer, Integer, Double, String, String, Double, Double, Integer, Double, Double> {

    private static final long serialVersionUID = 2118531551;

    /**
     * Setter for <code>handycapper.exotics.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.exotics.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.exotics.race_id</code>.
     */
    public void setRaceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.exotics.race_id</code>.
     */
    public Integer getRaceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>handycapper.exotics.unit</code>.
     */
    public void setUnit(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.exotics.unit</code>.
     */
    public Double getUnit() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>handycapper.exotics.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.exotics.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>handycapper.exotics.winning_numbers</code>.
     */
    public void setWinningNumbers(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.exotics.winning_numbers</code>.
     */
    public String getWinningNumbers() {
        return (String) get(4);
    }

    /**
     * Setter for <code>handycapper.exotics.payoff</code>.
     */
    public void setPayoff(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.exotics.payoff</code>.
     */
    public Double getPayoff() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>handycapper.exotics.odds</code>.
     */
    public void setOdds(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>handycapper.exotics.odds</code>.
     */
    public Double getOdds() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>handycapper.exotics.number_correct</code>.
     */
    public void setNumberCorrect(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>handycapper.exotics.number_correct</code>.
     */
    public Integer getNumberCorrect() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>handycapper.exotics.pool</code>.
     */
    public void setPool(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>handycapper.exotics.pool</code>.
     */
    public Double getPool() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>handycapper.exotics.carryover</code>.
     */
    public void setCarryover(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>handycapper.exotics.carryover</code>.
     */
    public Double getCarryover() {
        return (Double) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Double, String, String, Double, Double, Integer, Double, Double> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Double, String, String, Double, Double, Integer, Double, Double> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Exotics.EXOTICS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Exotics.EXOTICS.RACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Exotics.EXOTICS.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Exotics.EXOTICS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Exotics.EXOTICS.WINNING_NUMBERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Exotics.EXOTICS.PAYOFF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Exotics.EXOTICS.ODDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Exotics.EXOTICS.NUMBER_CORRECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return Exotics.EXOTICS.POOL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return Exotics.EXOTICS.CARRYOVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWinningNumbers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getPayoff();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getOdds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getNumberCorrect();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component9() {
        return getPool();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component10() {
        return getCarryover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWinningNumbers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getPayoff();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getOdds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getNumberCorrect();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getPool();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getCarryover();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value2(Integer value) {
        setRaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value3(Double value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value5(String value) {
        setWinningNumbers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value6(Double value) {
        setPayoff(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value7(Double value) {
        setOdds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value8(Integer value) {
        setNumberCorrect(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value9(Double value) {
        setPool(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord value10(Double value) {
        setCarryover(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExoticsRecord values(Integer value1, Integer value2, Double value3, String value4, String value5, Double value6, Double value7, Integer value8, Double value9, Double value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExoticsRecord
     */
    public ExoticsRecord() {
        super(Exotics.EXOTICS);
    }

    /**
     * Create a detached, initialised ExoticsRecord
     */
    public ExoticsRecord(Integer id, Integer raceId, Double unit, String name, String winningNumbers, Double payoff, Double odds, Integer numberCorrect, Double pool, Double carryover) {
        super(Exotics.EXOTICS);

        set(0, id);
        set(1, raceId);
        set(2, unit);
        set(3, name);
        set(4, winningNumbers);
        set(5, payoff);
        set(6, odds);
        set(7, numberCorrect);
        set(8, pool);
        set(9, carryover);
    }
}
