/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.Fractionals;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FractionalsRecord extends TableRecordImpl<FractionalsRecord> implements Record9<Integer, Integer, Integer, String, String, Integer, Double, String, Long> {

    private static final long serialVersionUID = -1317655829;

    /**
     * Setter for <code>handycapper.fractionals.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.fractionals.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.fractionals.race_id</code>.
     */
    public void setRaceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.fractionals.race_id</code>.
     */
    public Integer getRaceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>handycapper.fractionals.point</code>.
     */
    public void setPoint(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.fractionals.point</code>.
     */
    public Integer getPoint() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>handycapper.fractionals.text</code>.
     */
    public void setText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.fractionals.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>handycapper.fractionals.compact</code>.
     */
    public void setCompact(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.fractionals.compact</code>.
     */
    public String getCompact() {
        return (String) get(4);
    }

    /**
     * Setter for <code>handycapper.fractionals.feet</code>.
     */
    public void setFeet(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.fractionals.feet</code>.
     */
    public Integer getFeet() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>handycapper.fractionals.furlongs</code>.
     */
    public void setFurlongs(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>handycapper.fractionals.furlongs</code>.
     */
    public Double getFurlongs() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>handycapper.fractionals.time</code>.
     */
    public void setTime(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>handycapper.fractionals.time</code>.
     */
    public String getTime() {
        return (String) get(7);
    }

    /**
     * Setter for <code>handycapper.fractionals.millis</code>.
     */
    public void setMillis(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>handycapper.fractionals.millis</code>.
     */
    public Long getMillis() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, Integer, Double, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, Integer, String, String, Integer, Double, String, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Fractionals.FRACTIONALS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Fractionals.FRACTIONALS.RACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Fractionals.FRACTIONALS.POINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Fractionals.FRACTIONALS.TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Fractionals.FRACTIONALS.COMPACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Fractionals.FRACTIONALS.FEET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Fractionals.FRACTIONALS.FURLONGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Fractionals.FRACTIONALS.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Fractionals.FRACTIONALS.MILLIS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCompact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getFeet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getFurlongs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getMillis();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCompact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFeet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getFurlongs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getMillis();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord value2(Integer value) {
        setRaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord value3(Integer value) {
        setPoint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord value4(String value) {
        setText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord value5(String value) {
        setCompact(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord value6(Integer value) {
        setFeet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord value7(Double value) {
        setFurlongs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord value8(String value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord value9(Long value) {
        setMillis(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FractionalsRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6, Double value7, String value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FractionalsRecord
     */
    public FractionalsRecord() {
        super(Fractionals.FRACTIONALS);
    }

    /**
     * Create a detached, initialised FractionalsRecord
     */
    public FractionalsRecord(Integer id, Integer raceId, Integer point, String text, String compact, Integer feet, Double furlongs, String time, Long millis) {
        super(Fractionals.FRACTIONALS);

        set(0, id);
        set(1, raceId);
        set(2, point);
        set(3, text);
        set(4, compact);
        set(5, feet);
        set(6, furlongs);
        set(7, time);
        set(8, millis);
    }
}
