/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.IndivRatings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IndivRatingsRecord extends TableRecordImpl<IndivRatingsRecord> implements Record6<Integer, Integer, String, String, Double, String> {

    private static final long serialVersionUID = -1861942444;

    /**
     * Setter for <code>handycapper.indiv_ratings.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.indiv_ratings.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.indiv_ratings.starter_id</code>.
     */
    public void setStarterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.indiv_ratings.starter_id</code>.
     */
    public Integer getStarterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>handycapper.indiv_ratings.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.indiv_ratings.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>handycapper.indiv_ratings.text</code>.
     */
    public void setText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.indiv_ratings.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>handycapper.indiv_ratings.value</code>.
     */
    public void setValue(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.indiv_ratings.value</code>.
     */
    public Double getValue() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>handycapper.indiv_ratings.extra</code>.
     */
    public void setExtra(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.indiv_ratings.extra</code>.
     */
    public String getExtra() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, String, Double, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, String, Double, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return IndivRatings.INDIV_RATINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return IndivRatings.INDIV_RATINGS.STARTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return IndivRatings.INDIV_RATINGS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return IndivRatings.INDIV_RATINGS.TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return IndivRatings.INDIV_RATINGS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return IndivRatings.INDIV_RATINGS.EXTRA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getStarterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getExtra();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStarterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getExtra();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivRatingsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivRatingsRecord value2(Integer value) {
        setStarterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivRatingsRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivRatingsRecord value4(String value) {
        setText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivRatingsRecord value5(Double value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivRatingsRecord value6(String value) {
        setExtra(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public IndivRatingsRecord values(Integer value1, Integer value2, String value3, String value4, Double value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IndivRatingsRecord
     */
    public IndivRatingsRecord() {
        super(IndivRatings.INDIV_RATINGS);
    }

    /**
     * Create a detached, initialised IndivRatingsRecord
     */
    public IndivRatingsRecord(Integer id, Integer starterId, String name, String text, Double value, String extra) {
        super(IndivRatings.INDIV_RATINGS);

        set(0, id);
        set(1, starterId);
        set(2, name);
        set(3, text);
        set(4, value);
        set(5, extra);
    }
}
