/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.PointsOfCall;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PointsOfCallRecord extends TableRecordImpl<PointsOfCallRecord> implements Record13<Integer, Integer, Integer, String, String, Integer, Double, Integer, String, Double, String, Double, Integer> {

    private static final long serialVersionUID = 1322697754;

    /**
     * Setter for <code>handycapper.points_of_call.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.points_of_call.starter_id</code>.
     */
    public void setStarterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.starter_id</code>.
     */
    public Integer getStarterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>handycapper.points_of_call.point</code>.
     */
    public void setPoint(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.point</code>.
     */
    public Integer getPoint() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>handycapper.points_of_call.text</code>.
     */
    public void setText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>handycapper.points_of_call.compact</code>.
     */
    public void setCompact(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.compact</code>.
     */
    public String getCompact() {
        return (String) get(4);
    }

    /**
     * Setter for <code>handycapper.points_of_call.feet</code>.
     */
    public void setFeet(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.feet</code>.
     */
    public Integer getFeet() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>handycapper.points_of_call.furlongs</code>.
     */
    public void setFurlongs(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.furlongs</code>.
     */
    public Double getFurlongs() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>handycapper.points_of_call.position</code>.
     */
    public void setPosition(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>handycapper.points_of_call.len_ahead_text</code>.
     */
    public void setLenAheadText(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.len_ahead_text</code>.
     */
    public String getLenAheadText() {
        return (String) get(8);
    }

    /**
     * Setter for <code>handycapper.points_of_call.len_ahead</code>.
     */
    public void setLenAhead(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.len_ahead</code>.
     */
    public Double getLenAhead() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>handycapper.points_of_call.tot_len_bhd_text</code>.
     */
    public void setTotLenBhdText(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.tot_len_bhd_text</code>.
     */
    public String getTotLenBhdText() {
        return (String) get(10);
    }

    /**
     * Setter for <code>handycapper.points_of_call.tot_len_bhd</code>.
     */
    public void setTotLenBhd(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.tot_len_bhd</code>.
     */
    public Double getTotLenBhd() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>handycapper.points_of_call.wide</code>.
     */
    public void setWide(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>handycapper.points_of_call.wide</code>.
     */
    public Integer getWide() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, String, String, Integer, Double, Integer, String, Double, String, Double, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, String, String, Integer, Double, Integer, String, Double, String, Double, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PointsOfCall.POINTS_OF_CALL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PointsOfCall.POINTS_OF_CALL.STARTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PointsOfCall.POINTS_OF_CALL.POINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PointsOfCall.POINTS_OF_CALL.TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PointsOfCall.POINTS_OF_CALL.COMPACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return PointsOfCall.POINTS_OF_CALL.FEET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return PointsOfCall.POINTS_OF_CALL.FURLONGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return PointsOfCall.POINTS_OF_CALL.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return PointsOfCall.POINTS_OF_CALL.LEN_AHEAD_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return PointsOfCall.POINTS_OF_CALL.LEN_AHEAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return PointsOfCall.POINTS_OF_CALL.TOT_LEN_BHD_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field12() {
        return PointsOfCall.POINTS_OF_CALL.TOT_LEN_BHD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return PointsOfCall.POINTS_OF_CALL.WIDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getStarterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCompact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getFeet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getFurlongs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getLenAheadText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component10() {
        return getLenAhead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getTotLenBhdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component12() {
        return getTotLenBhd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getWide();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStarterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPoint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCompact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFeet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getFurlongs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getLenAheadText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getLenAhead();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getTotLenBhdText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value12() {
        return getTotLenBhd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getWide();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value2(Integer value) {
        setStarterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value3(Integer value) {
        setPoint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value4(String value) {
        setText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value5(String value) {
        setCompact(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value6(Integer value) {
        setFeet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value7(Double value) {
        setFurlongs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value8(Integer value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value9(String value) {
        setLenAheadText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value10(Double value) {
        setLenAhead(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value11(String value) {
        setTotLenBhdText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value12(Double value) {
        setTotLenBhd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord value13(Integer value) {
        setWide(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PointsOfCallRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6, Double value7, Integer value8, String value9, Double value10, String value11, Double value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PointsOfCallRecord
     */
    public PointsOfCallRecord() {
        super(PointsOfCall.POINTS_OF_CALL);
    }

    /**
     * Create a detached, initialised PointsOfCallRecord
     */
    public PointsOfCallRecord(Integer id, Integer starterId, Integer point, String text, String compact, Integer feet, Double furlongs, Integer position, String lenAheadText, Double lenAhead, String totLenBhdText, Double totLenBhd, Integer wide) {
        super(PointsOfCall.POINTS_OF_CALL);

        set(0, id);
        set(1, starterId);
        set(2, point);
        set(3, text);
        set(4, compact);
        set(5, feet);
        set(6, furlongs);
        set(7, position);
        set(8, lenAheadText);
        set(9, lenAhead);
        set(10, totLenBhdText);
        set(11, totLenBhd);
        set(12, wide);
    }
}
