/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.Races;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RacesRecord extends TableRecordImpl<RacesRecord> {

    private static final long serialVersionUID = -1131029986;

    /**
     * Setter for <code>handycapper.races.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.races.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.races.date</code>.
     */
    public void setDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.races.date</code>.
     */
    public Date getDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>handycapper.races.track</code>.
     */
    public void setTrack(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.races.track</code>.
     */
    public String getTrack() {
        return (String) get(2);
    }

    /**
     * Setter for <code>handycapper.races.track_canonical</code>.
     */
    public void setTrackCanonical(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.races.track_canonical</code>.
     */
    public String getTrackCanonical() {
        return (String) get(3);
    }

    /**
     * Setter for <code>handycapper.races.track_state</code>.
     */
    public void setTrackState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.races.track_state</code>.
     */
    public String getTrackState() {
        return (String) get(4);
    }

    /**
     * Setter for <code>handycapper.races.track_country</code>.
     */
    public void setTrackCountry(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.races.track_country</code>.
     */
    public String getTrackCountry() {
        return (String) get(5);
    }

    /**
     * Setter for <code>handycapper.races.track_name</code>.
     */
    public void setTrackName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>handycapper.races.track_name</code>.
     */
    public String getTrackName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>handycapper.races.number</code>.
     */
    public void setNumber(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>handycapper.races.number</code>.
     */
    public Integer getNumber() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>handycapper.races.breed</code>.
     */
    public void setBreed(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>handycapper.races.breed</code>.
     */
    public String getBreed() {
        return (String) get(8);
    }

    /**
     * Setter for <code>handycapper.races.type</code>.
     */
    public void setType(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>handycapper.races.type</code>.
     */
    public String getType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>handycapper.races.code</code>.
     */
    public void setCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>handycapper.races.code</code>.
     */
    public String getCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>handycapper.races.race_name</code>.
     */
    public void setRaceName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>handycapper.races.race_name</code>.
     */
    public String getRaceName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>handycapper.races.grade</code>.
     */
    public void setGrade(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>handycapper.races.grade</code>.
     */
    public Integer getGrade() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>handycapper.races.black_type</code>.
     */
    public void setBlackType(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>handycapper.races.black_type</code>.
     */
    public String getBlackType() {
        return (String) get(13);
    }

    /**
     * Setter for <code>handycapper.races.conditions</code>.
     */
    public void setConditions(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>handycapper.races.conditions</code>.
     */
    public String getConditions() {
        return (String) get(14);
    }

    /**
     * Setter for <code>handycapper.races.min_claim</code>.
     */
    public void setMinClaim(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>handycapper.races.min_claim</code>.
     */
    public Integer getMinClaim() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>handycapper.races.max_claim</code>.
     */
    public void setMaxClaim(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>handycapper.races.max_claim</code>.
     */
    public Integer getMaxClaim() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>handycapper.races.restrictions</code>.
     */
    public void setRestrictions(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>handycapper.races.restrictions</code>.
     */
    public String getRestrictions() {
        return (String) get(17);
    }

    /**
     * Setter for <code>handycapper.races.min_age</code>.
     */
    public void setMinAge(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>handycapper.races.min_age</code>.
     */
    public Integer getMinAge() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>handycapper.races.max_age</code>.
     */
    public void setMaxAge(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>handycapper.races.max_age</code>.
     */
    public Integer getMaxAge() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>handycapper.races.age_code</code>.
     */
    public void setAgeCode(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>handycapper.races.age_code</code>.
     */
    public String getAgeCode() {
        return (String) get(20);
    }

    /**
     * Setter for <code>handycapper.races.sexes</code>.
     */
    public void setSexes(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>handycapper.races.sexes</code>.
     */
    public Integer getSexes() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>handycapper.races.sexes_code</code>.
     */
    public void setSexesCode(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>handycapper.races.sexes_code</code>.
     */
    public String getSexesCode() {
        return (String) get(22);
    }

    /**
     * Setter for <code>handycapper.races.female_only</code>.
     */
    public void setFemaleOnly(Boolean value) {
        set(23, value);
    }

    /**
     * Getter for <code>handycapper.races.female_only</code>.
     */
    public Boolean getFemaleOnly() {
        return (Boolean) get(23);
    }

    /**
     * Setter for <code>handycapper.races.state_bred</code>.
     */
    public void setStateBred(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>handycapper.races.state_bred</code>.
     */
    public Boolean getStateBred() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>handycapper.races.distance_text</code>.
     */
    public void setDistanceText(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>handycapper.races.distance_text</code>.
     */
    public String getDistanceText() {
        return (String) get(25);
    }

    /**
     * Setter for <code>handycapper.races.distance_compact</code>.
     */
    public void setDistanceCompact(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>handycapper.races.distance_compact</code>.
     */
    public String getDistanceCompact() {
        return (String) get(26);
    }

    /**
     * Setter for <code>handycapper.races.feet</code>.
     */
    public void setFeet(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>handycapper.races.feet</code>.
     */
    public Integer getFeet() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>handycapper.races.furlongs</code>.
     */
    public void setFurlongs(Double value) {
        set(28, value);
    }

    /**
     * Getter for <code>handycapper.races.furlongs</code>.
     */
    public Double getFurlongs() {
        return (Double) get(28);
    }

    /**
     * Setter for <code>handycapper.races.exact</code>.
     */
    public void setExact(Boolean value) {
        set(29, value);
    }

    /**
     * Getter for <code>handycapper.races.exact</code>.
     */
    public Boolean getExact() {
        return (Boolean) get(29);
    }

    /**
     * Setter for <code>handycapper.races.run_up</code>.
     */
    public void setRunUp(Integer value) {
        set(30, value);
    }

    /**
     * Getter for <code>handycapper.races.run_up</code>.
     */
    public Integer getRunUp() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>handycapper.races.temp_rail</code>.
     */
    public void setTempRail(Integer value) {
        set(31, value);
    }

    /**
     * Getter for <code>handycapper.races.temp_rail</code>.
     */
    public Integer getTempRail() {
        return (Integer) get(31);
    }

    /**
     * Setter for <code>handycapper.races.surface</code>.
     */
    public void setSurface(String value) {
        set(32, value);
    }

    /**
     * Getter for <code>handycapper.races.surface</code>.
     */
    public String getSurface() {
        return (String) get(32);
    }

    /**
     * Setter for <code>handycapper.races.course</code>.
     */
    public void setCourse(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>handycapper.races.course</code>.
     */
    public String getCourse() {
        return (String) get(33);
    }

    /**
     * Setter for <code>handycapper.races.track_condition</code>.
     */
    public void setTrackCondition(String value) {
        set(34, value);
    }

    /**
     * Getter for <code>handycapper.races.track_condition</code>.
     */
    public String getTrackCondition() {
        return (String) get(34);
    }

    /**
     * Setter for <code>handycapper.races.scheduled_surface</code>.
     */
    public void setScheduledSurface(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>handycapper.races.scheduled_surface</code>.
     */
    public String getScheduledSurface() {
        return (String) get(35);
    }

    /**
     * Setter for <code>handycapper.races.scheduled_course</code>.
     */
    public void setScheduledCourse(String value) {
        set(36, value);
    }

    /**
     * Getter for <code>handycapper.races.scheduled_course</code>.
     */
    public String getScheduledCourse() {
        return (String) get(36);
    }

    /**
     * Setter for <code>handycapper.races.off_turf</code>.
     */
    public void setOffTurf(Boolean value) {
        set(37, value);
    }

    /**
     * Getter for <code>handycapper.races.off_turf</code>.
     */
    public Boolean getOffTurf() {
        return (Boolean) get(37);
    }

    /**
     * Setter for <code>handycapper.races.format</code>.
     */
    public void setFormat(String value) {
        set(38, value);
    }

    /**
     * Getter for <code>handycapper.races.format</code>.
     */
    public String getFormat() {
        return (String) get(38);
    }

    /**
     * Setter for <code>handycapper.races.track_record_holder</code>.
     */
    public void setTrackRecordHolder(String value) {
        set(39, value);
    }

    /**
     * Getter for <code>handycapper.races.track_record_holder</code>.
     */
    public String getTrackRecordHolder() {
        return (String) get(39);
    }

    /**
     * Setter for <code>handycapper.races.track_record_time</code>.
     */
    public void setTrackRecordTime(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>handycapper.races.track_record_time</code>.
     */
    public String getTrackRecordTime() {
        return (String) get(40);
    }

    /**
     * Setter for <code>handycapper.races.track_record_millis</code>.
     */
    public void setTrackRecordMillis(Long value) {
        set(41, value);
    }

    /**
     * Getter for <code>handycapper.races.track_record_millis</code>.
     */
    public Long getTrackRecordMillis() {
        return (Long) get(41);
    }

    /**
     * Setter for <code>handycapper.races.track_record_date</code>.
     */
    public void setTrackRecordDate(Date value) {
        set(42, value);
    }

    /**
     * Getter for <code>handycapper.races.track_record_date</code>.
     */
    public Date getTrackRecordDate() {
        return (Date) get(42);
    }

    /**
     * Setter for <code>handycapper.races.purse</code>.
     */
    public void setPurse(Integer value) {
        set(43, value);
    }

    /**
     * Getter for <code>handycapper.races.purse</code>.
     */
    public Integer getPurse() {
        return (Integer) get(43);
    }

    /**
     * Setter for <code>handycapper.races.purse_text</code>.
     */
    public void setPurseText(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>handycapper.races.purse_text</code>.
     */
    public String getPurseText() {
        return (String) get(44);
    }

    /**
     * Setter for <code>handycapper.races.available_money</code>.
     */
    public void setAvailableMoney(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>handycapper.races.available_money</code>.
     */
    public String getAvailableMoney() {
        return (String) get(45);
    }

    /**
     * Setter for <code>handycapper.races.purse_enhancements</code>.
     */
    public void setPurseEnhancements(String value) {
        set(46, value);
    }

    /**
     * Getter for <code>handycapper.races.purse_enhancements</code>.
     */
    public String getPurseEnhancements() {
        return (String) get(46);
    }

    /**
     * Setter for <code>handycapper.races.value_of_race</code>.
     */
    public void setValueOfRace(String value) {
        set(47, value);
    }

    /**
     * Getter for <code>handycapper.races.value_of_race</code>.
     */
    public String getValueOfRace() {
        return (String) get(47);
    }

    /**
     * Setter for <code>handycapper.races.weather</code>.
     */
    public void setWeather(String value) {
        set(48, value);
    }

    /**
     * Getter for <code>handycapper.races.weather</code>.
     */
    public String getWeather() {
        return (String) get(48);
    }

    /**
     * Setter for <code>handycapper.races.wind_speed</code>.
     */
    public void setWindSpeed(Integer value) {
        set(49, value);
    }

    /**
     * Getter for <code>handycapper.races.wind_speed</code>.
     */
    public Integer getWindSpeed() {
        return (Integer) get(49);
    }

    /**
     * Setter for <code>handycapper.races.wind_direction</code>.
     */
    public void setWindDirection(String value) {
        set(50, value);
    }

    /**
     * Getter for <code>handycapper.races.wind_direction</code>.
     */
    public String getWindDirection() {
        return (String) get(50);
    }

    /**
     * Setter for <code>handycapper.races.post_time</code>.
     */
    public void setPostTime(String value) {
        set(51, value);
    }

    /**
     * Getter for <code>handycapper.races.post_time</code>.
     */
    public String getPostTime() {
        return (String) get(51);
    }

    /**
     * Setter for <code>handycapper.races.start_comments</code>.
     */
    public void setStartComments(String value) {
        set(52, value);
    }

    /**
     * Getter for <code>handycapper.races.start_comments</code>.
     */
    public String getStartComments() {
        return (String) get(52);
    }

    /**
     * Setter for <code>handycapper.races.timer</code>.
     */
    public void setTimer(String value) {
        set(53, value);
    }

    /**
     * Getter for <code>handycapper.races.timer</code>.
     */
    public String getTimer() {
        return (String) get(53);
    }

    /**
     * Setter for <code>handycapper.races.dead_heat</code>.
     */
    public void setDeadHeat(Boolean value) {
        set(54, value);
    }

    /**
     * Getter for <code>handycapper.races.dead_heat</code>.
     */
    public Boolean getDeadHeat() {
        return (Boolean) get(54);
    }

    /**
     * Setter for <code>handycapper.races.number_of_runners</code>.
     */
    public void setNumberOfRunners(Integer value) {
        set(55, value);
    }

    /**
     * Getter for <code>handycapper.races.number_of_runners</code>.
     */
    public Integer getNumberOfRunners() {
        return (Integer) get(55);
    }

    /**
     * Setter for <code>handycapper.races.final_time</code>.
     */
    public void setFinalTime(String value) {
        set(56, value);
    }

    /**
     * Getter for <code>handycapper.races.final_time</code>.
     */
    public String getFinalTime() {
        return (String) get(56);
    }

    /**
     * Setter for <code>handycapper.races.final_millis</code>.
     */
    public void setFinalMillis(Long value) {
        set(57, value);
    }

    /**
     * Getter for <code>handycapper.races.final_millis</code>.
     */
    public Long getFinalMillis() {
        return (Long) get(57);
    }

    /**
     * Setter for <code>handycapper.races.total_wps_pool</code>.
     */
    public void setTotalWpsPool(Integer value) {
        set(58, value);
    }

    /**
     * Getter for <code>handycapper.races.total_wps_pool</code>.
     */
    public Integer getTotalWpsPool() {
        return (Integer) get(58);
    }

    /**
     * Setter for <code>handycapper.races.footnotes</code>.
     */
    public void setFootnotes(String value) {
        set(59, value);
    }

    /**
     * Getter for <code>handycapper.races.footnotes</code>.
     */
    public String getFootnotes() {
        return (String) get(59);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RacesRecord
     */
    public RacesRecord() {
        super(Races.RACES);
    }

    /**
     * Create a detached, initialised RacesRecord
     */
    public RacesRecord(Integer id, Date date, String track, String trackCanonical, String trackState, String trackCountry, String trackName, Integer number, String breed, String type, String code, String raceName, Integer grade, String blackType, String conditions, Integer minClaim, Integer maxClaim, String restrictions, Integer minAge, Integer maxAge, String ageCode, Integer sexes, String sexesCode, Boolean femaleOnly, Boolean stateBred, String distanceText, String distanceCompact, Integer feet, Double furlongs, Boolean exact, Integer runUp, Integer tempRail, String surface, String course, String trackCondition, String scheduledSurface, String scheduledCourse, Boolean offTurf, String format, String trackRecordHolder, String trackRecordTime, Long trackRecordMillis, Date trackRecordDate, Integer purse, String purseText, String availableMoney, String purseEnhancements, String valueOfRace, String weather, Integer windSpeed, String windDirection, String postTime, String startComments, String timer, Boolean deadHeat, Integer numberOfRunners, String finalTime, Long finalMillis, Integer totalWpsPool, String footnotes) {
        super(Races.RACES);

        set(0, id);
        set(1, date);
        set(2, track);
        set(3, trackCanonical);
        set(4, trackState);
        set(5, trackCountry);
        set(6, trackName);
        set(7, number);
        set(8, breed);
        set(9, type);
        set(10, code);
        set(11, raceName);
        set(12, grade);
        set(13, blackType);
        set(14, conditions);
        set(15, minClaim);
        set(16, maxClaim);
        set(17, restrictions);
        set(18, minAge);
        set(19, maxAge);
        set(20, ageCode);
        set(21, sexes);
        set(22, sexesCode);
        set(23, femaleOnly);
        set(24, stateBred);
        set(25, distanceText);
        set(26, distanceCompact);
        set(27, feet);
        set(28, furlongs);
        set(29, exact);
        set(30, runUp);
        set(31, tempRail);
        set(32, surface);
        set(33, course);
        set(34, trackCondition);
        set(35, scheduledSurface);
        set(36, scheduledCourse);
        set(37, offTurf);
        set(38, format);
        set(39, trackRecordHolder);
        set(40, trackRecordTime);
        set(41, trackRecordMillis);
        set(42, trackRecordDate);
        set(43, purse);
        set(44, purseText);
        set(45, availableMoney);
        set(46, purseEnhancements);
        set(47, valueOfRace);
        set(48, weather);
        set(49, windSpeed);
        set(50, windDirection);
        set(51, postTime);
        set(52, startComments);
        set(53, timer);
        set(54, deadHeat);
        set(55, numberOfRunners);
        set(56, finalTime);
        set(57, finalMillis);
        set(58, totalWpsPool);
        set(59, footnotes);
    }
}
