/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.Scratches;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScratchesRecord extends TableRecordImpl<ScratchesRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = 110638056;

    /**
     * Setter for <code>handycapper.scratches.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.scratches.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.scratches.race_id</code>.
     */
    public void setRaceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.scratches.race_id</code>.
     */
    public Integer getRaceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>handycapper.scratches.horse</code>.
     */
    public void setHorse(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.scratches.horse</code>.
     */
    public String getHorse() {
        return (String) get(2);
    }

    /**
     * Setter for <code>handycapper.scratches.reason</code>.
     */
    public void setReason(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.scratches.reason</code>.
     */
    public String getReason() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Scratches.SCRATCHES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Scratches.SCRATCHES.RACE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Scratches.SCRATCHES.HORSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Scratches.SCRATCHES.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getHorse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRaceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getHorse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScratchesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScratchesRecord value2(Integer value) {
        setRaceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScratchesRecord value3(String value) {
        setHorse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScratchesRecord value4(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScratchesRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScratchesRecord
     */
    public ScratchesRecord() {
        super(Scratches.SCRATCHES);
    }

    /**
     * Create a detached, initialised ScratchesRecord
     */
    public ScratchesRecord(Integer id, Integer raceId, String horse, String reason) {
        super(Scratches.SCRATCHES);

        set(0, id);
        set(1, raceId);
        set(2, horse);
        set(3, reason);
    }
}
