/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.Splits;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SplitsRecord extends TableRecordImpl<SplitsRecord> {

    private static final long serialVersionUID = -1280964793;

    /**
     * Setter for <code>handycapper.splits.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.splits.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.splits.race_id</code>.
     */
    public void setRaceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.splits.race_id</code>.
     */
    public Integer getRaceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>handycapper.splits.point</code>.
     */
    public void setPoint(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.splits.point</code>.
     */
    public Integer getPoint() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>handycapper.splits.text</code>.
     */
    public void setText(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.splits.text</code>.
     */
    public String getText() {
        return (String) get(3);
    }

    /**
     * Setter for <code>handycapper.splits.compact</code>.
     */
    public void setCompact(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.splits.compact</code>.
     */
    public String getCompact() {
        return (String) get(4);
    }

    /**
     * Setter for <code>handycapper.splits.feet</code>.
     */
    public void setFeet(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.splits.feet</code>.
     */
    public Integer getFeet() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>handycapper.splits.furlongs</code>.
     */
    public void setFurlongs(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>handycapper.splits.furlongs</code>.
     */
    public Double getFurlongs() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>handycapper.splits.time</code>.
     */
    public void setTime(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>handycapper.splits.time</code>.
     */
    public String getTime() {
        return (String) get(7);
    }

    /**
     * Setter for <code>handycapper.splits.millis</code>.
     */
    public void setMillis(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>handycapper.splits.millis</code>.
     */
    public Long getMillis() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>handycapper.splits.from_point</code>.
     */
    public void setFromPoint(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>handycapper.splits.from_point</code>.
     */
    public Integer getFromPoint() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>handycapper.splits.from_text</code>.
     */
    public void setFromText(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>handycapper.splits.from_text</code>.
     */
    public String getFromText() {
        return (String) get(10);
    }

    /**
     * Setter for <code>handycapper.splits.from_compact</code>.
     */
    public void setFromCompact(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>handycapper.splits.from_compact</code>.
     */
    public String getFromCompact() {
        return (String) get(11);
    }

    /**
     * Setter for <code>handycapper.splits.from_feet</code>.
     */
    public void setFromFeet(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>handycapper.splits.from_feet</code>.
     */
    public Integer getFromFeet() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>handycapper.splits.from_furlongs</code>.
     */
    public void setFromFurlongs(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>handycapper.splits.from_furlongs</code>.
     */
    public Double getFromFurlongs() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>handycapper.splits.from_time</code>.
     */
    public void setFromTime(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>handycapper.splits.from_time</code>.
     */
    public String getFromTime() {
        return (String) get(14);
    }

    /**
     * Setter for <code>handycapper.splits.from_millis</code>.
     */
    public void setFromMillis(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>handycapper.splits.from_millis</code>.
     */
    public Long getFromMillis() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>handycapper.splits.to_point</code>.
     */
    public void setToPoint(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>handycapper.splits.to_point</code>.
     */
    public Integer getToPoint() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>handycapper.splits.to_text</code>.
     */
    public void setToText(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>handycapper.splits.to_text</code>.
     */
    public String getToText() {
        return (String) get(17);
    }

    /**
     * Setter for <code>handycapper.splits.to_compact</code>.
     */
    public void setToCompact(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>handycapper.splits.to_compact</code>.
     */
    public String getToCompact() {
        return (String) get(18);
    }

    /**
     * Setter for <code>handycapper.splits.to_feet</code>.
     */
    public void setToFeet(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>handycapper.splits.to_feet</code>.
     */
    public Integer getToFeet() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>handycapper.splits.to_furlongs</code>.
     */
    public void setToFurlongs(Double value) {
        set(20, value);
    }

    /**
     * Getter for <code>handycapper.splits.to_furlongs</code>.
     */
    public Double getToFurlongs() {
        return (Double) get(20);
    }

    /**
     * Setter for <code>handycapper.splits.to_time</code>.
     */
    public void setToTime(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>handycapper.splits.to_time</code>.
     */
    public String getToTime() {
        return (String) get(21);
    }

    /**
     * Setter for <code>handycapper.splits.to_millis</code>.
     */
    public void setToMillis(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>handycapper.splits.to_millis</code>.
     */
    public Long getToMillis() {
        return (Long) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SplitsRecord
     */
    public SplitsRecord() {
        super(Splits.SPLITS);
    }

    /**
     * Create a detached, initialised SplitsRecord
     */
    public SplitsRecord(Integer id, Integer raceId, Integer point, String text, String compact, Integer feet, Double furlongs, String time, Long millis, Integer fromPoint, String fromText, String fromCompact, Integer fromFeet, Double fromFurlongs, String fromTime, Long fromMillis, Integer toPoint, String toText, String toCompact, Integer toFeet, Double toFurlongs, String toTime, Long toMillis) {
        super(Splits.SPLITS);

        set(0, id);
        set(1, raceId);
        set(2, point);
        set(3, text);
        set(4, compact);
        set(5, feet);
        set(6, furlongs);
        set(7, time);
        set(8, millis);
        set(9, fromPoint);
        set(10, fromText);
        set(11, fromCompact);
        set(12, fromFeet);
        set(13, fromFurlongs);
        set(14, fromTime);
        set(15, fromMillis);
        set(16, toPoint);
        set(17, toText);
        set(18, toCompact);
        set(19, toFeet);
        set(20, toFurlongs);
        set(21, toTime);
        set(22, toMillis);
    }
}
