/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.Starters;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StartersRecord extends TableRecordImpl<StartersRecord> {

    private static final long serialVersionUID = 500441917;

    /**
     * Setter for <code>handycapper.starters.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.starters.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.starters.race_id</code>.
     */
    public void setRaceId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.starters.race_id</code>.
     */
    public Integer getRaceId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>handycapper.starters.last_raced_date</code>.
     */
    public void setLastRacedDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.starters.last_raced_date</code>.
     */
    public Date getLastRacedDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>handycapper.starters.last_raced_days_since</code>.
     */
    public void setLastRacedDaysSince(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.starters.last_raced_days_since</code>.
     */
    public Integer getLastRacedDaysSince() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>handycapper.starters.last_raced_track</code>.
     */
    public void setLastRacedTrack(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.starters.last_raced_track</code>.
     */
    public String getLastRacedTrack() {
        return (String) get(4);
    }

    /**
     * Setter for <code>handycapper.starters.last_raced_track_canonical</code>.
     */
    public void setLastRacedTrackCanonical(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.starters.last_raced_track_canonical</code>.
     */
    public String getLastRacedTrackCanonical() {
        return (String) get(5);
    }

    /**
     * Setter for <code>handycapper.starters.last_raced_track_state</code>.
     */
    public void setLastRacedTrackState(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>handycapper.starters.last_raced_track_state</code>.
     */
    public String getLastRacedTrackState() {
        return (String) get(6);
    }

    /**
     * Setter for <code>handycapper.starters.last_raced_track_country</code>.
     */
    public void setLastRacedTrackCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>handycapper.starters.last_raced_track_country</code>.
     */
    public String getLastRacedTrackCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>handycapper.starters.last_raced_track_name</code>.
     */
    public void setLastRacedTrackName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>handycapper.starters.last_raced_track_name</code>.
     */
    public String getLastRacedTrackName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>handycapper.starters.last_raced_number</code>.
     */
    public void setLastRacedNumber(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>handycapper.starters.last_raced_number</code>.
     */
    public Integer getLastRacedNumber() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>handycapper.starters.last_raced_position</code>.
     */
    public void setLastRacedPosition(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>handycapper.starters.last_raced_position</code>.
     */
    public Integer getLastRacedPosition() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>handycapper.starters.program</code>.
     */
    public void setProgram(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>handycapper.starters.program</code>.
     */
    public String getProgram() {
        return (String) get(11);
    }

    /**
     * Setter for <code>handycapper.starters.entry</code>.
     */
    public void setEntry(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>handycapper.starters.entry</code>.
     */
    public Boolean getEntry() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>handycapper.starters.entry_program</code>.
     */
    public void setEntryProgram(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>handycapper.starters.entry_program</code>.
     */
    public String getEntryProgram() {
        return (String) get(13);
    }

    /**
     * Setter for <code>handycapper.starters.horse</code>.
     */
    public void setHorse(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>handycapper.starters.horse</code>.
     */
    public String getHorse() {
        return (String) get(14);
    }

    /**
     * Setter for <code>handycapper.starters.jockey_first</code>.
     */
    public void setJockeyFirst(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>handycapper.starters.jockey_first</code>.
     */
    public String getJockeyFirst() {
        return (String) get(15);
    }

    /**
     * Setter for <code>handycapper.starters.jockey_last</code>.
     */
    public void setJockeyLast(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>handycapper.starters.jockey_last</code>.
     */
    public String getJockeyLast() {
        return (String) get(16);
    }

    /**
     * Setter for <code>handycapper.starters.trainer_first</code>.
     */
    public void setTrainerFirst(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>handycapper.starters.trainer_first</code>.
     */
    public String getTrainerFirst() {
        return (String) get(17);
    }

    /**
     * Setter for <code>handycapper.starters.trainer_last</code>.
     */
    public void setTrainerLast(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>handycapper.starters.trainer_last</code>.
     */
    public String getTrainerLast() {
        return (String) get(18);
    }

    /**
     * Setter for <code>handycapper.starters.owner</code>.
     */
    public void setOwner(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>handycapper.starters.owner</code>.
     */
    public String getOwner() {
        return (String) get(19);
    }

    /**
     * Setter for <code>handycapper.starters.weight</code>.
     */
    public void setWeight(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>handycapper.starters.weight</code>.
     */
    public Integer getWeight() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>handycapper.starters.jockey_allowance</code>.
     */
    public void setJockeyAllowance(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>handycapper.starters.jockey_allowance</code>.
     */
    public Integer getJockeyAllowance() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>handycapper.starters.medication_equipment</code>.
     */
    public void setMedicationEquipment(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>handycapper.starters.medication_equipment</code>.
     */
    public String getMedicationEquipment() {
        return (String) get(22);
    }

    /**
     * Setter for <code>handycapper.starters.claim_price</code>.
     */
    public void setClaimPrice(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>handycapper.starters.claim_price</code>.
     */
    public Integer getClaimPrice() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>handycapper.starters.claimed</code>.
     */
    public void setClaimed(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>handycapper.starters.claimed</code>.
     */
    public Boolean getClaimed() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>handycapper.starters.new_trainer_name</code>.
     */
    public void setNewTrainerName(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>handycapper.starters.new_trainer_name</code>.
     */
    public String getNewTrainerName() {
        return (String) get(25);
    }

    /**
     * Setter for <code>handycapper.starters.new_owner_name</code>.
     */
    public void setNewOwnerName(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>handycapper.starters.new_owner_name</code>.
     */
    public String getNewOwnerName() {
        return (String) get(26);
    }

    /**
     * Setter for <code>handycapper.starters.pp</code>.
     */
    public void setPp(Integer value) {
        set(27, value);
    }

    /**
     * Getter for <code>handycapper.starters.pp</code>.
     */
    public Integer getPp() {
        return (Integer) get(27);
    }

    /**
     * Setter for <code>handycapper.starters.finish_position</code>.
     */
    public void setFinishPosition(Integer value) {
        set(28, value);
    }

    /**
     * Getter for <code>handycapper.starters.finish_position</code>.
     */
    public Integer getFinishPosition() {
        return (Integer) get(28);
    }

    /**
     * Setter for <code>handycapper.starters.official_position</code>.
     */
    public void setOfficialPosition(Integer value) {
        set(29, value);
    }

    /**
     * Getter for <code>handycapper.starters.official_position</code>.
     */
    public Integer getOfficialPosition() {
        return (Integer) get(29);
    }

    /**
     * Setter for <code>handycapper.starters.position_dead_heat</code>.
     */
    public void setPositionDeadHeat(Boolean value) {
        set(30, value);
    }

    /**
     * Getter for <code>handycapper.starters.position_dead_heat</code>.
     */
    public Boolean getPositionDeadHeat() {
        return (Boolean) get(30);
    }

    /**
     * Setter for <code>handycapper.starters.wagering_position</code>.
     */
    public void setWageringPosition(Integer value) {
        set(31, value);
    }

    /**
     * Getter for <code>handycapper.starters.wagering_position</code>.
     */
    public Integer getWageringPosition() {
        return (Integer) get(31);
    }

    /**
     * Setter for <code>handycapper.starters.winner</code>.
     */
    public void setWinner(Boolean value) {
        set(32, value);
    }

    /**
     * Getter for <code>handycapper.starters.winner</code>.
     */
    public Boolean getWinner() {
        return (Boolean) get(32);
    }

    /**
     * Setter for <code>handycapper.starters.disqualified</code>.
     */
    public void setDisqualified(Boolean value) {
        set(33, value);
    }

    /**
     * Getter for <code>handycapper.starters.disqualified</code>.
     */
    public Boolean getDisqualified() {
        return (Boolean) get(33);
    }

    /**
     * Setter for <code>handycapper.starters.odds</code>.
     */
    public void setOdds(Double value) {
        set(34, value);
    }

    /**
     * Getter for <code>handycapper.starters.odds</code>.
     */
    public Double getOdds() {
        return (Double) get(34);
    }

    /**
     * Setter for <code>handycapper.starters.choice</code>.
     */
    public void setChoice(Integer value) {
        set(35, value);
    }

    /**
     * Getter for <code>handycapper.starters.choice</code>.
     */
    public Integer getChoice() {
        return (Integer) get(35);
    }

    /**
     * Setter for <code>handycapper.starters.favorite</code>.
     */
    public void setFavorite(Boolean value) {
        set(36, value);
    }

    /**
     * Getter for <code>handycapper.starters.favorite</code>.
     */
    public Boolean getFavorite() {
        return (Boolean) get(36);
    }

    /**
     * Setter for <code>handycapper.starters.comments</code>.
     */
    public void setComments(String value) {
        set(37, value);
    }

    /**
     * Getter for <code>handycapper.starters.comments</code>.
     */
    public String getComments() {
        return (String) get(37);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StartersRecord
     */
    public StartersRecord() {
        super(Starters.STARTERS);
    }

    /**
     * Create a detached, initialised StartersRecord
     */
    public StartersRecord(Integer id, Integer raceId, Date lastRacedDate, Integer lastRacedDaysSince, String lastRacedTrack, String lastRacedTrackCanonical, String lastRacedTrackState, String lastRacedTrackCountry, String lastRacedTrackName, Integer lastRacedNumber, Integer lastRacedPosition, String program, Boolean entry, String entryProgram, String horse, String jockeyFirst, String jockeyLast, String trainerFirst, String trainerLast, String owner, Integer weight, Integer jockeyAllowance, String medicationEquipment, Integer claimPrice, Boolean claimed, String newTrainerName, String newOwnerName, Integer pp, Integer finishPosition, Integer officialPosition, Boolean positionDeadHeat, Integer wageringPosition, Boolean winner, Boolean disqualified, Double odds, Integer choice, Boolean favorite, String comments) {
        super(Starters.STARTERS);

        set(0, id);
        set(1, raceId);
        set(2, lastRacedDate);
        set(3, lastRacedDaysSince);
        set(4, lastRacedTrack);
        set(5, lastRacedTrackCanonical);
        set(6, lastRacedTrackState);
        set(7, lastRacedTrackCountry);
        set(8, lastRacedTrackName);
        set(9, lastRacedNumber);
        set(10, lastRacedPosition);
        set(11, program);
        set(12, entry);
        set(13, entryProgram);
        set(14, horse);
        set(15, jockeyFirst);
        set(16, jockeyLast);
        set(17, trainerFirst);
        set(18, trainerLast);
        set(19, owner);
        set(20, weight);
        set(21, jockeyAllowance);
        set(22, medicationEquipment);
        set(23, claimPrice);
        set(24, claimed);
        set(25, newTrainerName);
        set(26, newOwnerName);
        set(27, pp);
        set(28, finishPosition);
        set(29, officialPosition);
        set(30, positionDeadHeat);
        set(31, wageringPosition);
        set(32, winner);
        set(33, disqualified);
        set(34, odds);
        set(35, choice);
        set(36, favorite);
        set(37, comments);
    }
}
