/*
 * This file is generated by jOOQ.
*/
package com.robinhowlett.handycapper.domain.tables.records;


import com.robinhowlett.handycapper.domain.tables.Wps;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WpsRecord extends TableRecordImpl<WpsRecord> implements Record6<Integer, Integer, String, Double, Double, Double> {

    private static final long serialVersionUID = -532662016;

    /**
     * Setter for <code>handycapper.wps.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>handycapper.wps.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>handycapper.wps.starter_id</code>.
     */
    public void setStarterId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>handycapper.wps.starter_id</code>.
     */
    public Integer getStarterId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>handycapper.wps.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>handycapper.wps.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>handycapper.wps.unit</code>.
     */
    public void setUnit(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>handycapper.wps.unit</code>.
     */
    public Double getUnit() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>handycapper.wps.payoff</code>.
     */
    public void setPayoff(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>handycapper.wps.payoff</code>.
     */
    public Double getPayoff() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>handycapper.wps.odds</code>.
     */
    public void setOdds(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>handycapper.wps.odds</code>.
     */
    public Double getOdds() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Double, Double, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, String, Double, Double, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Wps.WPS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Wps.WPS.STARTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Wps.WPS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Wps.WPS.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Wps.WPS.PAYOFF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Wps.WPS.ODDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getStarterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getPayoff();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getOdds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStarterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getPayoff();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getOdds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WpsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WpsRecord value2(Integer value) {
        setStarterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WpsRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WpsRecord value4(Double value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WpsRecord value5(Double value) {
        setPayoff(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WpsRecord value6(Double value) {
        setOdds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WpsRecord values(Integer value1, Integer value2, String value3, Double value4, Double value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WpsRecord
     */
    public WpsRecord() {
        super(Wps.WPS);
    }

    /**
     * Create a detached, initialised WpsRecord
     */
    public WpsRecord(Integer id, Integer starterId, String type, Double unit, Double payoff, Double odds) {
        super(Wps.WPS);

        set(0, id);
        set(1, starterId);
        set(2, type);
        set(3, unit);
        set(4, payoff);
        set(5, odds);
    }
}
